package entity

import (
	"time"

	"github.com/finance_app/backend/internal/domain"
)

// ImpersonationSession maps to the impersonation_sessions table. The ID is a
// UUID (string) generated by the service before insert, not an auto-increment.
type ImpersonationSession struct {
	ID           string
	AdminUserID  int
	TargetUserID int
	Reason       string
	IPAddress    *string
	UserAgent    *string
	CreatedAt    time.Time
	ExpiresAt    time.Time
	RevokedAt    *time.Time
}

func (s *ImpersonationSession) ToDomain() *domain.ImpersonationSession {
	out := &domain.ImpersonationSession{
		ID:           s.ID,
		AdminUserID:  s.AdminUserID,
		TargetUserID: s.TargetUserID,
		Reason:       s.Reason,
		CreatedAt:    s.CreatedAt,
		ExpiresAt:    s.ExpiresAt,
		RevokedAt:    s.RevokedAt,
	}
	if s.IPAddress != nil {
		out.IPAddress = *s.IPAddress
	}
	if s.UserAgent != nil {
		out.UserAgent = *s.UserAgent
	}
	return out
}

func ImpersonationSessionFromDomain(d *domain.ImpersonationSession) *ImpersonationSession {
	ent := &ImpersonationSession{
		ID:           d.ID,
		AdminUserID:  d.AdminUserID,
		TargetUserID: d.TargetUserID,
		Reason:       d.Reason,
		CreatedAt:    d.CreatedAt,
		ExpiresAt:    d.ExpiresAt,
		RevokedAt:    d.RevokedAt,
	}
	if d.IPAddress != "" {
		ent.IPAddress = &d.IPAddress
	}
	if d.UserAgent != "" {
		ent.UserAgent = &d.UserAgent
	}
	return ent
}
