export const NotificationsTestIds = {
  SwitchNotifications: 'switch_notifications',
  RowNotifications: 'row_notifications',
  HelperNotifications: 'text_notifications_helper',
  Drawer: 'drawer_notifications',
  DrawerClose: 'btn_notifications_close',
  BtnMarkAllRead: 'btn_mark_all_read',
  BtnDeleteRead: 'btn_delete_read_notifications',
  ConfirmDeleteReadDrawer: 'drawer_confirm_delete_read',
  ConfirmDeleteReadConfirm: 'btn_confirm_delete_read',
  RowBtnDelete: (id: number) => `btn_delete_notification_${id}` as const,
  RowBtnMarkRead: (id: number) => `btn_mark_read_notification_${id}` as const,
  BtnLoadMore: 'btn_notifications_load_more',
  EmptyState: 'section_notifications_empty',
  ErrorState: 'section_notifications_error',
  BtnRetry: 'btn_notifications_retry',
  Row: (id: number) => `notification_row_${id}` as const,
  UnreadDot: (id: number) => `notification_unread_dot_${id}` as const,
  NavBellDesktop: 'nav_bell_desktop',
  MaisTabIndicator: 'mobile_mais_tab_indicator',
  MoreDrawerNotificationsItem: 'more_drawer_notifications_item',
} as const
