export type TransactionType = 'expense' | 'income' | 'transfer'
export type PropagationOption = 'current' | 'current_and_future' | 'all'
export type TransactionFilterKind = 'accounts' | 'categories' | 'tags'
export type TransactionExtraPanel = 'tags' | 'recurrence' | 'split'

export const TransactionsTestIds = {
  // Page-level
  BtnNew: 'btn_new_transaction',
  BtnSave: 'btn_save_transaction',
  BtnMoreOptions: 'btn_more_options',
  MenuItemImportTransactions: 'menu_item_import_transactions',
  Checkbox: (txId: number | string) => `checkbox_${txId}` as const,
  CheckboxSettlement: (settlementId: number | string) => `checkbox_settlement_${settlementId}` as const,
  SettlementRow: (settlementId: number | string) => `row_settlement_${settlementId}` as const,
  /** Group header for a TransactionGroup; key matches group.key (label string). */
  GroupHeader: (key: string) => `group_header_${key}` as const,
  InputSplitDate: (rowIndex: number | string) => `input_split_date_${rowIndex}` as const,

  // Drawers (create / update / linked)
  DrawerCreate: 'drawer_create_transaction',
  DrawerUpdate: 'drawer_update_transaction',
  DrawerUpdateLinkedSplit: 'drawer_update_linked_split',
  DrawerUpdateLinkedTransfer: 'drawer_update_linked_transfer',

  // Form errors
  AlertFormError: 'alert_form_error',
  // Info shown when editing a transfer generated by a charge (cobrança)
  AlertChargeInfo: 'alert_charge_info',

  // Form fields
  InputAmount: 'input_amount',
  InputDescription: 'input_description',
  SelectAccount: 'select_account',
  SelectDestinationAccount: 'select_destination_account',
  SelectCategory: 'select_category',
  // Read-only account display shown when the source/destination account can't
  // be edited (partner-owned, or a shared account on a charge-settlement transfer).
  ReadOnlyAccount: 'readonly_account',
  ReadOnlyDestinationAccount: 'readonly_destination_account',
  SegmentedTransactionType: 'segmented_transaction_type',
  // Read-only type display shown when the type can't be changed (charge transfers)
  InputTransactionType: 'input_transaction_type',

  // Select options (renderOption testids — pass the entity id)
  OptionAccount: (accountId: number | string) => `option_account_${accountId}` as const,
  OptionDestinationAccount: (accountId: number | string) =>
    `option_destination_account_${accountId}` as const,
  OptionCategory: (categoryId: number | string) => `option_category_${categoryId}` as const,
  OptionDescriptionSuggestion: (description: string) =>
    `option_description_suggestion_${description}` as const,

  // SegmentedControl items
  SegmentTransactionType: (type: TransactionType) => `segment_transaction_type_${type}` as const,
  SegmentGroupBy: (option: 'date' | 'category' | 'account') =>
    `segment_group_by_${option}` as const,

  // Tags
  TagsInput: 'input_tags',

  // Extra sections accordion (tags / recurrence / split). Names kept from the
  // previous SegmentedControl-based UI so e2e selectors don't need a rename.
  SegmentedExtraSections: 'segmented_extra_sections',
  SegmentExtraSection: (panel: TransactionExtraPanel) =>
    `segment_extra_section_${panel}` as const,
  SwitchRecurrenceEnabled: 'switch_recurrence_enabled',

  // Date quick-shortcut chips below the date picker.
  DateChip: (key: 'today' | 'yesterday' | 'day_before') =>
    `chip_date_${key}` as const,

  // Split
  InputSplitAmount: 'input_split_amount',
  InputSplitPercentage: 'input_split_percentage',
  BtnAddSplitRow: 'btn_add_split_row',
  SplitRowPreview: (rowIndex: number | string) => `text_split_preview_${rowIndex}` as const,
  SplitSumFooter: 'text_split_sum_footer',
  SegmentedSplitMode: 'segmented_split_mode',
  SegmentSplitMode: (mode: 'percentage' | 'amount') => `segment_split_mode_${mode}` as const,

  // Transfer row avatar pair
  TransferAvatarGroup: 'transfer_avatar_group',
  IconTransferArrow: 'icon_transfer_arrow',

  // Filters (top-level)
  InputTextSearch: 'input_text_search',
  SegmentedGroupBy: 'segmented_group_by',
  BtnGroupByMenu: 'btn_group_by_menu',
  MenuItemGroupBy: (option: 'date' | 'category' | 'account') =>
    `menu_item_group_by_${option}` as const,
  AdvancedFiltersPopover: 'advanced_filters_popover',
  BtnOpenAdvancedFilters: 'open_advanced_filters',
  SwitchType: (type: TransactionType) => `switch_type_${type}` as const,
  SwitchHideSettlements: 'switch_hide_settlements',
  BtnClearFilters: 'btn_clear_filters',

  // Mobile filter row (search + 2 icon buttons that open drawers)
  BtnOpenFiltersDrawer: 'btn_open_filters_drawer',
  BtnOpenCategoriesFilterDrawer: 'btn_open_categories_filter_drawer',
  DrawerFilters: 'drawer_filters',
  DrawerCategoriesFilter: 'drawer_categories_filter',

  // Per-kind filter Popover triggers + dropdowns
  BtnFilter: (kind: TransactionFilterKind) => `btn_filter_${kind}` as const,
  PopoverFilter: (kind: TransactionFilterKind) => `popover_filter_${kind}` as const,

  // Filter entries (scoped inside the Popover)
  CheckboxFilterAccount: (accountId: number | string) =>
    `checkbox_filter_account_${accountId}` as const,
  CheckboxFilterCategory: (categoryId: number | string) =>
    `checkbox_filter_category_${categoryId}` as const,
  BadgeFilterTag: (tagId: number | string) => `badge_filter_tag_${tagId}` as const,

  // Mobile swipe-to-delete (per row)
  BtnSwipeDelete: (txId: number | string) => `btn_swipe_delete_${txId}` as const,

  // Selection & bulk menu
  SelectionActionBar: 'selection_action_bar',
  SelectionCount: 'selection_count',
  BtnClearSelection: 'btn_clear_selection',
  BtnBulkActionsMenu: 'btn_bulk_actions_menu',
  BtnBulkCategory: 'btn_bulk_category',
  BtnBulkDate: 'btn_bulk_date',
  BtnBulkDivision: 'btn_bulk_division',
  BtnBulkDelete: 'btn_bulk_delete',
  HintBulkDivisionNoConnection: 'hint_bulk_division_no_connection',

  // Bulk progress drawer (root testid; overridden per flow via testIdPrefix)
  BulkProgressDrawer: 'bulk_progress',
  BulkDeleteDrawer: 'bulk_delete',
  BulkCategoryDrawer: 'bulk_category',
  BulkDateDrawer: 'bulk_date',
  BulkDivisionProgressDrawer: 'bulk_division',
  BulkProgressBar: 'bulk_progress_bar',
  BulkCurrentLabel: 'bulk_current_label',
  BulkSuccess: 'bulk_success',
  BulkError: 'bulk_error',
  BtnBulkDone: 'btn_bulk_done',
  BtnBulkCloseError: 'btn_bulk_close_error',

  // Bulk division drawer
  DrawerBulkDivision: 'drawer_bulk_division',
  BtnApplyBulkDivision: 'btn_apply_bulk_division',

  // Select category / date drawers
  DrawerSelectCategory: 'drawer_select_category',
  DrawerSelectDate: 'drawer_select_date',
  InputBulkDate: 'input_bulk_date',
  BtnApplyDate: 'btn_apply_date',
  CategoryOption: (categoryId: number | string) =>
    `category_option_${categoryId}` as const,

  // Propagation
  PropagationDrawerBody: 'propagation_drawer_body',
  PropagationOption: (opt: PropagationOption) => `propagation_option_${opt}` as const,
  PropagationUpdateOption: (opt: PropagationOption) =>
    `propagation_update_option_${opt}` as const,

  // Amount calculator
  BtnOpenCalculator: 'btn_open_calculator',
  DrawerCalculator: 'drawer_calculator',
  CalcDisplay: 'calculator_display',
  CalcExpression: 'calculator_expression',
  BtnCalcApply: 'btn_calculator_apply',
  BtnCalcCancel: 'btn_calculator_cancel',
  CalcKey: (key: string) => `calc_key_${key}` as const,
} as const
