// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionTemplateRepository is an autogenerated mock type for the TransactionTemplateRepository type
type MockTransactionTemplateRepository struct {
	mock.Mock
}

type MockTransactionTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionTemplateRepository) EXPECT() *MockTransactionTemplateRepository_Expecter {
	return &MockTransactionTemplateRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, t
func (_m *MockTransactionTemplateRepository) Create(ctx context.Context, t *domain.TransactionTemplate) (*domain.TransactionTemplate, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.TransactionTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransactionTemplate) (*domain.TransactionTemplate, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransactionTemplate) *domain.TransactionTemplate); ok {
		r0 = rf(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransactionTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.TransactionTemplate) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionTemplateRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionTemplateRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t *domain.TransactionTemplate
func (_e *MockTransactionTemplateRepository_Expecter) Create(ctx interface{}, t interface{}) *MockTransactionTemplateRepository_Create_Call {
	return &MockTransactionTemplateRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockTransactionTemplateRepository_Create_Call) Run(run func(ctx context.Context, t *domain.TransactionTemplate)) *MockTransactionTemplateRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.TransactionTemplate))
	})
	return _c
}

func (_c *MockTransactionTemplateRepository_Create_Call) Return(_a0 *domain.TransactionTemplate, _a1 error) *MockTransactionTemplateRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionTemplateRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.TransactionTemplate) (*domain.TransactionTemplate, error)) *MockTransactionTemplateRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *MockTransactionTemplateRepository) Delete(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionTemplateRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionTemplateRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockTransactionTemplateRepository_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockTransactionTemplateRepository_Delete_Call {
	return &MockTransactionTemplateRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockTransactionTemplateRepository_Delete_Call) Run(run func(ctx context.Context, userID int, id int)) *MockTransactionTemplateRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionTemplateRepository_Delete_Call) Return(_a0 error) *MockTransactionTemplateRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionTemplateRepository_Delete_Call) RunAndReturn(run func(context.Context, int, int) error) *MockTransactionTemplateRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDForUser provides a mock function with given fields: ctx, userID, id
func (_m *MockTransactionTemplateRepository) GetByIDForUser(ctx context.Context, userID int, id int) (*domain.TransactionTemplate, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDForUser")
	}

	var r0 *domain.TransactionTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*domain.TransactionTemplate, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *domain.TransactionTemplate); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransactionTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionTemplateRepository_GetByIDForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDForUser'
type MockTransactionTemplateRepository_GetByIDForUser_Call struct {
	*mock.Call
}

// GetByIDForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockTransactionTemplateRepository_Expecter) GetByIDForUser(ctx interface{}, userID interface{}, id interface{}) *MockTransactionTemplateRepository_GetByIDForUser_Call {
	return &MockTransactionTemplateRepository_GetByIDForUser_Call{Call: _e.mock.On("GetByIDForUser", ctx, userID, id)}
}

func (_c *MockTransactionTemplateRepository_GetByIDForUser_Call) Run(run func(ctx context.Context, userID int, id int)) *MockTransactionTemplateRepository_GetByIDForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionTemplateRepository_GetByIDForUser_Call) Return(_a0 *domain.TransactionTemplate, _a1 error) *MockTransactionTemplateRepository_GetByIDForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionTemplateRepository_GetByIDForUser_Call) RunAndReturn(run func(context.Context, int, int) (*domain.TransactionTemplate, error)) *MockTransactionTemplateRepository_GetByIDForUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *MockTransactionTemplateRepository) ListByUserID(ctx context.Context, userID int) ([]*domain.TransactionTemplate, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*domain.TransactionTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.TransactionTemplate, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.TransactionTemplate); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TransactionTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionTemplateRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockTransactionTemplateRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockTransactionTemplateRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockTransactionTemplateRepository_ListByUserID_Call {
	return &MockTransactionTemplateRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockTransactionTemplateRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockTransactionTemplateRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionTemplateRepository_ListByUserID_Call) Return(_a0 []*domain.TransactionTemplate, _a1 error) *MockTransactionTemplateRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionTemplateRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, int) ([]*domain.TransactionTemplate, error)) *MockTransactionTemplateRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, t
func (_m *MockTransactionTemplateRepository) Update(ctx context.Context, userID int, t *domain.TransactionTemplate) error {
	ret := _m.Called(ctx, userID, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.TransactionTemplate) error); ok {
		r0 = rf(ctx, userID, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionTemplateRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionTemplateRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - t *domain.TransactionTemplate
func (_e *MockTransactionTemplateRepository_Expecter) Update(ctx interface{}, userID interface{}, t interface{}) *MockTransactionTemplateRepository_Update_Call {
	return &MockTransactionTemplateRepository_Update_Call{Call: _e.mock.On("Update", ctx, userID, t)}
}

func (_c *MockTransactionTemplateRepository_Update_Call) Run(run func(ctx context.Context, userID int, t *domain.TransactionTemplate)) *MockTransactionTemplateRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.TransactionTemplate))
	})
	return _c
}

func (_c *MockTransactionTemplateRepository_Update_Call) Return(_a0 error) *MockTransactionTemplateRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionTemplateRepository_Update_Call) RunAndReturn(run func(context.Context, int, *domain.TransactionTemplate) error) *MockTransactionTemplateRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionTemplateRepository creates a new instance of MockTransactionTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionTemplateRepository {
	mock := &MockTransactionTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
