// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockNotificationRepository is an autogenerated mock type for the NotificationRepository type
type MockNotificationRepository struct {
	mock.Mock
}

type MockNotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationRepository) EXPECT() *MockNotificationRepository_Expecter {
	return &MockNotificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, notification
func (_m *MockNotificationRepository) Create(ctx context.Context, notification *domain.Notification) (*domain.Notification, error) {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Notification) (*domain.Notification, error)); ok {
		return rf(ctx, notification)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Notification) *domain.Notification); ok {
		r0 = rf(ctx, notification)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Notification) error); ok {
		r1 = rf(ctx, notification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNotificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - notification *domain.Notification
func (_e *MockNotificationRepository_Expecter) Create(ctx interface{}, notification interface{}) *MockNotificationRepository_Create_Call {
	return &MockNotificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, notification)}
}

func (_c *MockNotificationRepository_Create_Call) Run(run func(ctx context.Context, notification *domain.Notification)) *MockNotificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Notification))
	})
	return _c
}

func (_c *MockNotificationRepository_Create_Call) Return(_a0 *domain.Notification, _a1 error) *MockNotificationRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Notification) (*domain.Notification, error)) *MockNotificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockNotificationRepository) List(ctx context.Context, filter domain.NotificationFilter) (*domain.NotificationListResult, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.NotificationListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.NotificationFilter) (*domain.NotificationListResult, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.NotificationFilter) *domain.NotificationListResult); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotificationListResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.NotificationFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockNotificationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.NotificationFilter
func (_e *MockNotificationRepository_Expecter) List(ctx interface{}, filter interface{}) *MockNotificationRepository_List_Call {
	return &MockNotificationRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockNotificationRepository_List_Call) Run(run func(ctx context.Context, filter domain.NotificationFilter)) *MockNotificationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.NotificationFilter))
	})
	return _c
}

func (_c *MockNotificationRepository_List_Call) Return(_a0 *domain.NotificationListResult, _a1 error) *MockNotificationRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_List_Call) RunAndReturn(run func(context.Context, domain.NotificationFilter) (*domain.NotificationListResult, error)) *MockNotificationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function with given fields: ctx, userID
func (_m *MockNotificationRepository) MarkAllRead(ctx context.Context, userID int) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationRepository_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type MockNotificationRepository_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockNotificationRepository_Expecter) MarkAllRead(ctx interface{}, userID interface{}) *MockNotificationRepository_MarkAllRead_Call {
	return &MockNotificationRepository_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userID)}
}

func (_c *MockNotificationRepository_MarkAllRead_Call) Run(run func(ctx context.Context, userID int)) *MockNotificationRepository_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockNotificationRepository_MarkAllRead_Call) Return(_a0 error) *MockNotificationRepository_MarkAllRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationRepository_MarkAllRead_Call) RunAndReturn(run func(context.Context, int) error) *MockNotificationRepository_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function with given fields: ctx, userID, notificationID
func (_m *MockNotificationRepository) MarkRead(ctx context.Context, userID int, notificationID int) error {
	ret := _m.Called(ctx, userID, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, notificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationRepository_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockNotificationRepository_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - notificationID int
func (_e *MockNotificationRepository_Expecter) MarkRead(ctx interface{}, userID interface{}, notificationID interface{}) *MockNotificationRepository_MarkRead_Call {
	return &MockNotificationRepository_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, userID, notificationID)}
}

func (_c *MockNotificationRepository_MarkRead_Call) Run(run func(ctx context.Context, userID int, notificationID int)) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockNotificationRepository_MarkRead_Call) Return(_a0 error) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationRepository_MarkRead_Call) RunAndReturn(run func(context.Context, int, int) error) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// UnreadCount provides a mock function with given fields: ctx, userID
func (_m *MockNotificationRepository) UnreadCount(ctx context.Context, userID int) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnreadCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepository_UnreadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnreadCount'
type MockNotificationRepository_UnreadCount_Call struct {
	*mock.Call
}

// UnreadCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockNotificationRepository_Expecter) UnreadCount(ctx interface{}, userID interface{}) *MockNotificationRepository_UnreadCount_Call {
	return &MockNotificationRepository_UnreadCount_Call{Call: _e.mock.On("UnreadCount", ctx, userID)}
}

func (_c *MockNotificationRepository_UnreadCount_Call) Run(run func(ctx context.Context, userID int)) *MockNotificationRepository_UnreadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockNotificationRepository_UnreadCount_Call) Return(_a0 int64, _a1 error) *MockNotificationRepository_UnreadCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepository_UnreadCount_Call) RunAndReturn(run func(context.Context, int) (int64, error)) *MockNotificationRepository_UnreadCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationRepository creates a new instance of MockNotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationRepository {
	mock := &MockNotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
