// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockImpersonationService is an autogenerated mock type for the ImpersonationService type
type MockImpersonationService struct {
	mock.Mock
}

type MockImpersonationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImpersonationService) EXPECT() *MockImpersonationService_Expecter {
	return &MockImpersonationService_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with given fields: ctx, adminUserID, targetUserID, reason, ipAddress, userAgent
func (_m *MockImpersonationService) Start(ctx context.Context, adminUserID int, targetUserID int, reason string, ipAddress string, userAgent string) (*domain.StartImpersonationResult, error) {
	ret := _m.Called(ctx, adminUserID, targetUserID, reason, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *domain.StartImpersonationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string) (*domain.StartImpersonationResult, error)); ok {
		return rf(ctx, adminUserID, targetUserID, reason, ipAddress, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string) *domain.StartImpersonationResult); ok {
		r0 = rf(ctx, adminUserID, targetUserID, reason, ipAddress, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StartImpersonationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string) error); ok {
		r1 = rf(ctx, adminUserID, targetUserID, reason, ipAddress, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImpersonationService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockImpersonationService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - adminUserID int
//   - targetUserID int
//   - reason string
//   - ipAddress string
//   - userAgent string
func (_e *MockImpersonationService_Expecter) Start(ctx interface{}, adminUserID interface{}, targetUserID interface{}, reason interface{}, ipAddress interface{}, userAgent interface{}) *MockImpersonationService_Start_Call {
	return &MockImpersonationService_Start_Call{Call: _e.mock.On("Start", ctx, adminUserID, targetUserID, reason, ipAddress, userAgent)}
}

func (_c *MockImpersonationService_Start_Call) Run(run func(ctx context.Context, adminUserID int, targetUserID int, reason string, ipAddress string, userAgent string)) *MockImpersonationService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockImpersonationService_Start_Call) Return(_a0 *domain.StartImpersonationResult, _a1 error) *MockImpersonationService_Start_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImpersonationService_Start_Call) RunAndReturn(run func(context.Context, int, int, string, string, string) (*domain.StartImpersonationResult, error)) *MockImpersonationService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: ctx, sessionID, actorAdminID
func (_m *MockImpersonationService) Stop(ctx context.Context, sessionID string, actorAdminID int) error {
	ret := _m.Called(ctx, sessionID, actorAdminID)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, sessionID, actorAdminID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockImpersonationService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockImpersonationService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - actorAdminID int
func (_e *MockImpersonationService_Expecter) Stop(ctx interface{}, sessionID interface{}, actorAdminID interface{}) *MockImpersonationService_Stop_Call {
	return &MockImpersonationService_Stop_Call{Call: _e.mock.On("Stop", ctx, sessionID, actorAdminID)}
}

func (_c *MockImpersonationService_Stop_Call) Run(run func(ctx context.Context, sessionID string, actorAdminID int)) *MockImpersonationService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockImpersonationService_Stop_Call) Return(_a0 error) *MockImpersonationService_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImpersonationService_Stop_Call) RunAndReturn(run func(context.Context, string, int) error) *MockImpersonationService_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, query, limit
func (_m *MockImpersonationService) SearchUsers(ctx context.Context, query string, limit int) ([]*domain.User, error) {
	ret := _m.Called(ctx, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]*domain.User, error)); ok {
		return rf(ctx, query, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*domain.User); ok {
		r0 = rf(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImpersonationService_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockImpersonationService_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
func (_e *MockImpersonationService_Expecter) SearchUsers(ctx interface{}, query interface{}, limit interface{}) *MockImpersonationService_SearchUsers_Call {
	return &MockImpersonationService_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, query, limit)}
}

func (_c *MockImpersonationService_SearchUsers_Call) Run(run func(ctx context.Context, query string, limit int)) *MockImpersonationService_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockImpersonationService_SearchUsers_Call) Return(_a0 []*domain.User, _a1 error) *MockImpersonationService_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImpersonationService_SearchUsers_Call) RunAndReturn(run func(context.Context, string, int) ([]*domain.User, error)) *MockImpersonationService_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImpersonationService creates a new instance of MockImpersonationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImpersonationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImpersonationService {
	mock := &MockImpersonationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
