// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// AcceptSharedAccount provides a mock function with given fields: ctx, userID, id
func (_m *MockAccountService) AcceptSharedAccount(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for AcceptSharedAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountService_AcceptSharedAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptSharedAccount'
type MockAccountService_AcceptSharedAccount_Call struct {
	*mock.Call
}

// AcceptSharedAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockAccountService_Expecter) AcceptSharedAccount(ctx interface{}, userID interface{}, id interface{}) *MockAccountService_AcceptSharedAccount_Call {
	return &MockAccountService_AcceptSharedAccount_Call{Call: _e.mock.On("AcceptSharedAccount", ctx, userID, id)}
}

func (_c *MockAccountService_AcceptSharedAccount_Call) Run(run func(ctx context.Context, userID int, id int)) *MockAccountService_AcceptSharedAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAccountService_AcceptSharedAccount_Call) Return(_a0 error) *MockAccountService_AcceptSharedAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountService_AcceptSharedAccount_Call) RunAndReturn(run func(context.Context, int, int) error) *MockAccountService_AcceptSharedAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userID, account
func (_m *MockAccountService) Create(ctx context.Context, userID int, account *domain.Account) (*domain.Account, error) {
	ret := _m.Called(ctx, userID, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Account) (*domain.Account, error)); ok {
		return rf(ctx, userID, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Account) *domain.Account); ok {
		r0 = rf(ctx, userID, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *domain.Account) error); ok {
		r1 = rf(ctx, userID, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - account *domain.Account
func (_e *MockAccountService_Expecter) Create(ctx interface{}, userID interface{}, account interface{}) *MockAccountService_Create_Call {
	return &MockAccountService_Create_Call{Call: _e.mock.On("Create", ctx, userID, account)}
}

func (_c *MockAccountService_Create_Call) Run(run func(ctx context.Context, userID int, account *domain.Account)) *MockAccountService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Account))
	})
	return _c
}

func (_c *MockAccountService_Create_Call) Return(_a0 *domain.Account, _a1 error) *MockAccountService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_Create_Call) RunAndReturn(run func(context.Context, int, *domain.Account) (*domain.Account, error)) *MockAccountService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *MockAccountService) Delete(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockAccountService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockAccountService_Delete_Call {
	return &MockAccountService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockAccountService_Delete_Call) Run(run func(ctx context.Context, userID int, id int)) *MockAccountService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAccountService_Delete_Call) Return(_a0 error) *MockAccountService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountService_Delete_Call) RunAndReturn(run func(context.Context, int, int) error) *MockAccountService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *MockAccountService) GetByID(ctx context.Context, userID int, id int) (*domain.Account, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*domain.Account, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *domain.Account); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAccountService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockAccountService_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *MockAccountService_GetByID_Call {
	return &MockAccountService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *MockAccountService_GetByID_Call) Run(run func(ctx context.Context, userID int, id int)) *MockAccountService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAccountService_GetByID_Call) Return(_a0 *domain.Account, _a1 error) *MockAccountService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_GetByID_Call) RunAndReturn(run func(context.Context, int, int) (*domain.Account, error)) *MockAccountService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID
func (_m *MockAccountService) List(ctx context.Context, userID int) ([]*domain.Account, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Account, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Account); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAccountService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockAccountService_Expecter) List(ctx interface{}, userID interface{}) *MockAccountService_List_Call {
	return &MockAccountService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockAccountService_List_Call) Run(run func(ctx context.Context, userID int)) *MockAccountService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAccountService_List_Call) Return(_a0 []*domain.Account, _a1 error) *MockAccountService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_List_Call) RunAndReturn(run func(context.Context, int) ([]*domain.Account, error)) *MockAccountService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, account
func (_m *MockAccountService) Update(ctx context.Context, userID int, account *domain.Account) error {
	ret := _m.Called(ctx, userID, account)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Account) error); ok {
		r0 = rf(ctx, userID, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - account *domain.Account
func (_e *MockAccountService_Expecter) Update(ctx interface{}, userID interface{}, account interface{}) *MockAccountService_Update_Call {
	return &MockAccountService_Update_Call{Call: _e.mock.On("Update", ctx, userID, account)}
}

func (_c *MockAccountService_Update_Call) Run(run func(ctx context.Context, userID int, account *domain.Account)) *MockAccountService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Account))
	})
	return _c
}

func (_c *MockAccountService_Update_Call) Return(_a0 error) *MockAccountService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountService_Update_Call) RunAndReturn(run func(context.Context, int, *domain.Account) error) *MockAccountService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
