// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockOnboardingService is an autogenerated mock type for the OnboardingService type
type MockOnboardingService struct {
	mock.Mock
}

type MockOnboardingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnboardingService) EXPECT() *MockOnboardingService_Expecter {
	return &MockOnboardingService_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx, userID, req
func (_m *MockOnboardingService) Complete(ctx context.Context, userID int, req *domain.OnboardingSetupRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.OnboardingSetupRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOnboardingService_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockOnboardingService_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - req *domain.OnboardingSetupRequest
func (_e *MockOnboardingService_Expecter) Complete(ctx interface{}, userID interface{}, req interface{}) *MockOnboardingService_Complete_Call {
	return &MockOnboardingService_Complete_Call{Call: _e.mock.On("Complete", ctx, userID, req)}
}

func (_c *MockOnboardingService_Complete_Call) Run(run func(ctx context.Context, userID int, req *domain.OnboardingSetupRequest)) *MockOnboardingService_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.OnboardingSetupRequest))
	})
	return _c
}

func (_c *MockOnboardingService_Complete_Call) Return(_a0 error) *MockOnboardingService_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnboardingService_Complete_Call) RunAndReturn(run func(context.Context, int, *domain.OnboardingSetupRequest) error) *MockOnboardingService_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: ctx, userID
func (_m *MockOnboardingService) GetStatus(ctx context.Context, userID int) (*domain.OnboardingStatus, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *domain.OnboardingStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.OnboardingStatus, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.OnboardingStatus); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OnboardingStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOnboardingService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockOnboardingService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockOnboardingService_Expecter) GetStatus(ctx interface{}, userID interface{}) *MockOnboardingService_GetStatus_Call {
	return &MockOnboardingService_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, userID)}
}

func (_c *MockOnboardingService_GetStatus_Call) Run(run func(ctx context.Context, userID int)) *MockOnboardingService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockOnboardingService_GetStatus_Call) Return(_a0 *domain.OnboardingStatus, _a1 error) *MockOnboardingService_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOnboardingService_GetStatus_Call) RunAndReturn(run func(context.Context, int) (*domain.OnboardingStatus, error)) *MockOnboardingService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnboardingService creates a new instance of MockOnboardingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnboardingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnboardingService {
	mock := &MockOnboardingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
