// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTagService is an autogenerated mock type for the TagService type
type MockTagService struct {
	mock.Mock
}

type MockTagService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagService) EXPECT() *MockTagService_Expecter {
	return &MockTagService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, tag
func (_m *MockTagService) Create(ctx context.Context, userID int, tag *domain.Tag) (*domain.Tag, error) {
	ret := _m.Called(ctx, userID, tag)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Tag) (*domain.Tag, error)); ok {
		return rf(ctx, userID, tag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Tag) *domain.Tag); ok {
		r0 = rf(ctx, userID, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *domain.Tag) error); ok {
		r1 = rf(ctx, userID, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTagService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - tag *domain.Tag
func (_e *MockTagService_Expecter) Create(ctx interface{}, userID interface{}, tag interface{}) *MockTagService_Create_Call {
	return &MockTagService_Create_Call{Call: _e.mock.On("Create", ctx, userID, tag)}
}

func (_c *MockTagService_Create_Call) Run(run func(ctx context.Context, userID int, tag *domain.Tag)) *MockTagService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Tag))
	})
	return _c
}

func (_c *MockTagService_Create_Call) Return(_a0 *domain.Tag, _a1 error) *MockTagService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagService_Create_Call) RunAndReturn(run func(context.Context, int, *domain.Tag) (*domain.Tag, error)) *MockTagService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *MockTagService) Delete(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTagService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockTagService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockTagService_Delete_Call {
	return &MockTagService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockTagService_Delete_Call) Run(run func(ctx context.Context, userID int, id int)) *MockTagService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTagService_Delete_Call) Return(_a0 error) *MockTagService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagService_Delete_Call) RunAndReturn(run func(context.Context, int, int) error) *MockTagService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *MockTagService) GetByID(ctx context.Context, userID int, id int) (*domain.Tag, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*domain.Tag, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *domain.Tag); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTagService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockTagService_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *MockTagService_GetByID_Call {
	return &MockTagService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *MockTagService_GetByID_Call) Run(run func(ctx context.Context, userID int, id int)) *MockTagService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTagService_GetByID_Call) Return(_a0 *domain.Tag, _a1 error) *MockTagService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagService_GetByID_Call) RunAndReturn(run func(context.Context, int, int) (*domain.Tag, error)) *MockTagService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID
func (_m *MockTagService) List(ctx context.Context, userID int) ([]*domain.Tag, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Tag, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Tag); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTagService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockTagService_Expecter) List(ctx interface{}, userID interface{}) *MockTagService_List_Call {
	return &MockTagService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockTagService_List_Call) Run(run func(ctx context.Context, userID int)) *MockTagService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTagService_List_Call) Return(_a0 []*domain.Tag, _a1 error) *MockTagService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagService_List_Call) RunAndReturn(run func(context.Context, int) ([]*domain.Tag, error)) *MockTagService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, tag
func (_m *MockTagService) Update(ctx context.Context, userID int, tag *domain.Tag) error {
	ret := _m.Called(ctx, userID, tag)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Tag) error); ok {
		r0 = rf(ctx, userID, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTagService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - tag *domain.Tag
func (_e *MockTagService_Expecter) Update(ctx interface{}, userID interface{}, tag interface{}) *MockTagService_Update_Call {
	return &MockTagService_Update_Call{Call: _e.mock.On("Update", ctx, userID, tag)}
}

func (_c *MockTagService_Update_Call) Run(run func(ctx context.Context, userID int, tag *domain.Tag)) *MockTagService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Tag))
	})
	return _c
}

func (_c *MockTagService_Update_Call) Return(_a0 error) *MockTagService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagService_Update_Call) RunAndReturn(run func(context.Context, int, *domain.Tag) error) *MockTagService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagService creates a new instance of MockTagService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagService {
	mock := &MockTagService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
