// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTagRepository is an autogenerated mock type for the TagRepository type
type MockTagRepository struct {
	mock.Mock
}

type MockTagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagRepository) EXPECT() *MockTagRepository_Expecter {
	return &MockTagRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tag
func (_m *MockTagRepository) Create(ctx context.Context, tag *domain.Tag) (*domain.Tag, error) {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tag) (*domain.Tag, error)); ok {
		return rf(ctx, tag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tag) *domain.Tag); ok {
		r0 = rf(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Tag) error); ok {
		r1 = rf(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTagRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tag *domain.Tag
func (_e *MockTagRepository_Expecter) Create(ctx interface{}, tag interface{}) *MockTagRepository_Create_Call {
	return &MockTagRepository_Create_Call{Call: _e.mock.On("Create", ctx, tag)}
}

func (_c *MockTagRepository_Create_Call) Run(run func(ctx context.Context, tag *domain.Tag)) *MockTagRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Tag))
	})
	return _c
}

func (_c *MockTagRepository_Create_Call) Return(_a0 *domain.Tag, _a1 error) *MockTagRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Tag) (*domain.Tag, error)) *MockTagRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTagRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTagRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTagRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTagRepository_Delete_Call {
	return &MockTagRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTagRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockTagRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTagRepository_Delete_Call) Return(_a0 error) *MockTagRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockTagRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, options
func (_m *MockTagRepository) Search(ctx context.Context, options domain.TagSearchOptions) ([]*domain.Tag, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TagSearchOptions) ([]*domain.Tag, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TagSearchOptions) []*domain.Tag); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TagSearchOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockTagRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - options domain.TagSearchOptions
func (_e *MockTagRepository_Expecter) Search(ctx interface{}, options interface{}) *MockTagRepository_Search_Call {
	return &MockTagRepository_Search_Call{Call: _e.mock.On("Search", ctx, options)}
}

func (_c *MockTagRepository_Search_Call) Run(run func(ctx context.Context, options domain.TagSearchOptions)) *MockTagRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TagSearchOptions))
	})
	return _c
}

func (_c *MockTagRepository_Search_Call) Return(_a0 []*domain.Tag, _a1 error) *MockTagRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagRepository_Search_Call) RunAndReturn(run func(context.Context, domain.TagSearchOptions) ([]*domain.Tag, error)) *MockTagRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, tag
func (_m *MockTagRepository) Update(ctx context.Context, tag *domain.Tag) error {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tag) error); ok {
		r0 = rf(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTagRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tag *domain.Tag
func (_e *MockTagRepository_Expecter) Update(ctx interface{}, tag interface{}) *MockTagRepository_Update_Call {
	return &MockTagRepository_Update_Call{Call: _e.mock.On("Update", ctx, tag)}
}

func (_c *MockTagRepository_Update_Call) Run(run func(ctx context.Context, tag *domain.Tag)) *MockTagRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Tag))
	})
	return _c
}

func (_c *MockTagRepository_Update_Call) Return(_a0 error) *MockTagRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Tag) error) *MockTagRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagRepository creates a new instance of MockTagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagRepository {
	mock := &MockTagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
