// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockChargeService is an autogenerated mock type for the ChargeService type
type MockChargeService struct {
	mock.Mock
}

type MockChargeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChargeService) EXPECT() *MockChargeService_Expecter {
	return &MockChargeService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, callerUserID, chargeID
func (_m *MockChargeService) Cancel(ctx context.Context, callerUserID int, chargeID int) error {
	ret := _m.Called(ctx, callerUserID, chargeID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, callerUserID, chargeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChargeService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockChargeService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - callerUserID int
//   - chargeID int
func (_e *MockChargeService_Expecter) Cancel(ctx interface{}, callerUserID interface{}, chargeID interface{}) *MockChargeService_Cancel_Call {
	return &MockChargeService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, callerUserID, chargeID)}
}

func (_c *MockChargeService_Cancel_Call) Run(run func(ctx context.Context, callerUserID int, chargeID int)) *MockChargeService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockChargeService_Cancel_Call) Return(_a0 error) *MockChargeService_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChargeService_Cancel_Call) RunAndReturn(run func(context.Context, int, int) error) *MockChargeService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, callerUserID, req
func (_m *MockChargeService) Create(ctx context.Context, callerUserID int, req *domain.CreateChargeRequest) (*domain.Charge, error) {
	ret := _m.Called(ctx, callerUserID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Charge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.CreateChargeRequest) (*domain.Charge, error)); ok {
		return rf(ctx, callerUserID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.CreateChargeRequest) *domain.Charge); ok {
		r0 = rf(ctx, callerUserID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Charge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *domain.CreateChargeRequest) error); ok {
		r1 = rf(ctx, callerUserID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChargeService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChargeService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - callerUserID int
//   - req *domain.CreateChargeRequest
func (_e *MockChargeService_Expecter) Create(ctx interface{}, callerUserID interface{}, req interface{}) *MockChargeService_Create_Call {
	return &MockChargeService_Create_Call{Call: _e.mock.On("Create", ctx, callerUserID, req)}
}

func (_c *MockChargeService_Create_Call) Run(run func(ctx context.Context, callerUserID int, req *domain.CreateChargeRequest)) *MockChargeService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.CreateChargeRequest))
	})
	return _c
}

func (_c *MockChargeService_Create_Call) Return(_a0 *domain.Charge, _a1 error) *MockChargeService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChargeService_Create_Call) RunAndReturn(run func(context.Context, int, *domain.CreateChargeRequest) (*domain.Charge, error)) *MockChargeService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, options
func (_m *MockChargeService) List(ctx context.Context, options domain.ChargeSearchOptions) ([]*domain.Charge, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Charge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChargeSearchOptions) ([]*domain.Charge, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChargeSearchOptions) []*domain.Charge); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Charge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ChargeSearchOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChargeService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockChargeService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - options domain.ChargeSearchOptions
func (_e *MockChargeService_Expecter) List(ctx interface{}, options interface{}) *MockChargeService_List_Call {
	return &MockChargeService_List_Call{Call: _e.mock.On("List", ctx, options)}
}

func (_c *MockChargeService_List_Call) Run(run func(ctx context.Context, options domain.ChargeSearchOptions)) *MockChargeService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ChargeSearchOptions))
	})
	return _c
}

func (_c *MockChargeService_List_Call) Return(_a0 []*domain.Charge, _a1 error) *MockChargeService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChargeService_List_Call) RunAndReturn(run func(context.Context, domain.ChargeSearchOptions) ([]*domain.Charge, error)) *MockChargeService_List_Call {
	_c.Call.Return(run)
	return _c
}

// PendingCount provides a mock function with given fields: ctx, callerUserID
func (_m *MockChargeService) PendingCount(ctx context.Context, callerUserID int) (int64, error) {
	ret := _m.Called(ctx, callerUserID)

	if len(ret) == 0 {
		panic("no return value specified for PendingCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return rf(ctx, callerUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, callerUserID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, callerUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChargeService_PendingCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingCount'
type MockChargeService_PendingCount_Call struct {
	*mock.Call
}

// PendingCount is a helper method to define mock.On call
//   - ctx context.Context
//   - callerUserID int
func (_e *MockChargeService_Expecter) PendingCount(ctx interface{}, callerUserID interface{}) *MockChargeService_PendingCount_Call {
	return &MockChargeService_PendingCount_Call{Call: _e.mock.On("PendingCount", ctx, callerUserID)}
}

func (_c *MockChargeService_PendingCount_Call) Run(run func(ctx context.Context, callerUserID int)) *MockChargeService_PendingCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockChargeService_PendingCount_Call) Return(_a0 int64, _a1 error) *MockChargeService_PendingCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChargeService_PendingCount_Call) RunAndReturn(run func(context.Context, int) (int64, error)) *MockChargeService_PendingCount_Call {
	_c.Call.Return(run)
	return _c
}

// Reject provides a mock function with given fields: ctx, callerUserID, chargeID
func (_m *MockChargeService) Reject(ctx context.Context, callerUserID int, chargeID int) error {
	ret := _m.Called(ctx, callerUserID, chargeID)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, callerUserID, chargeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChargeService_Reject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reject'
type MockChargeService_Reject_Call struct {
	*mock.Call
}

// Reject is a helper method to define mock.On call
//   - ctx context.Context
//   - callerUserID int
//   - chargeID int
func (_e *MockChargeService_Expecter) Reject(ctx interface{}, callerUserID interface{}, chargeID interface{}) *MockChargeService_Reject_Call {
	return &MockChargeService_Reject_Call{Call: _e.mock.On("Reject", ctx, callerUserID, chargeID)}
}

func (_c *MockChargeService_Reject_Call) Run(run func(ctx context.Context, callerUserID int, chargeID int)) *MockChargeService_Reject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockChargeService_Reject_Call) Return(_a0 error) *MockChargeService_Reject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChargeService_Reject_Call) RunAndReturn(run func(context.Context, int, int) error) *MockChargeService_Reject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChargeService creates a new instance of MockChargeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChargeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChargeService {
	mock := &MockChargeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
