// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionService is an autogenerated mock type for the TransactionService type
type MockTransactionService struct {
	mock.Mock
}

type MockTransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionService) EXPECT() *MockTransactionService_Expecter {
	return &MockTransactionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, transaction
func (_m *MockTransactionService) Create(ctx context.Context, userID int, transaction *domain.TransactionCreateRequest) (int, error) {
	ret := _m.Called(ctx, userID, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.TransactionCreateRequest) (int, error)); ok {
		return rf(ctx, userID, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.TransactionCreateRequest) int); ok {
		r0 = rf(ctx, userID, transaction)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *domain.TransactionCreateRequest) error); ok {
		r1 = rf(ctx, userID, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - transaction *domain.TransactionCreateRequest
func (_e *MockTransactionService_Expecter) Create(ctx interface{}, userID interface{}, transaction interface{}) *MockTransactionService_Create_Call {
	return &MockTransactionService_Create_Call{Call: _e.mock.On("Create", ctx, userID, transaction)}
}

func (_c *MockTransactionService_Create_Call) Run(run func(ctx context.Context, userID int, transaction *domain.TransactionCreateRequest)) *MockTransactionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.TransactionCreateRequest))
	})
	return _c
}

func (_c *MockTransactionService_Create_Call) Return(_a0 int, _a1 error) *MockTransactionService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_Create_Call) RunAndReturn(run func(context.Context, int, *domain.TransactionCreateRequest) (int, error)) *MockTransactionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id, propagationSettings
func (_m *MockTransactionService) Delete(ctx context.Context, userID int, id int, propagationSettings domain.TransactionPropagationSettings) error {
	ret := _m.Called(ctx, userID, id, propagationSettings)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, domain.TransactionPropagationSettings) error); ok {
		r0 = rf(ctx, userID, id, propagationSettings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
//   - propagationSettings domain.TransactionPropagationSettings
func (_e *MockTransactionService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}, propagationSettings interface{}) *MockTransactionService_Delete_Call {
	return &MockTransactionService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id, propagationSettings)}
}

func (_c *MockTransactionService_Delete_Call) Run(run func(ctx context.Context, userID int, id int, propagationSettings domain.TransactionPropagationSettings)) *MockTransactionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(domain.TransactionPropagationSettings))
	})
	return _c
}

func (_c *MockTransactionService_Delete_Call) Return(_a0 error) *MockTransactionService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionService_Delete_Call) RunAndReturn(run func(context.Context, int, int, domain.TransactionPropagationSettings) error) *MockTransactionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx, userID, period, filter
func (_m *MockTransactionService) GetBalance(ctx context.Context, userID int, period domain.Period, filter domain.BalanceFilter) (*domain.BalanceResult, error) {
	ret := _m.Called(ctx, userID, period, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *domain.BalanceResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.Period, domain.BalanceFilter) (*domain.BalanceResult, error)); ok {
		return rf(ctx, userID, period, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.Period, domain.BalanceFilter) *domain.BalanceResult); ok {
		r0 = rf(ctx, userID, period, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BalanceResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, domain.Period, domain.BalanceFilter) error); ok {
		r1 = rf(ctx, userID, period, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockTransactionService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - period domain.Period
//   - filter domain.BalanceFilter
func (_e *MockTransactionService_Expecter) GetBalance(ctx interface{}, userID interface{}, period interface{}, filter interface{}) *MockTransactionService_GetBalance_Call {
	return &MockTransactionService_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID, period, filter)}
}

func (_c *MockTransactionService_GetBalance_Call) Run(run func(ctx context.Context, userID int, period domain.Period, filter domain.BalanceFilter)) *MockTransactionService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(domain.Period), args[3].(domain.BalanceFilter))
	})
	return _c
}

func (_c *MockTransactionService_GetBalance_Call) Return(_a0 *domain.BalanceResult, _a1 error) *MockTransactionService_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_GetBalance_Call) RunAndReturn(run func(context.Context, int, domain.Period, domain.BalanceFilter) (*domain.BalanceResult, error)) *MockTransactionService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ParseImportCSV provides a mock function with given fields: ctx, userID, accountID, csvData
func (_m *MockTransactionService) ParseImportCSV(ctx context.Context, userID int, accountID int, csvData []byte) (*domain.ImportCSVResponse, error) {
	ret := _m.Called(ctx, userID, accountID, csvData)

	if len(ret) == 0 {
		panic("no return value specified for ParseImportCSV")
	}

	var r0 *domain.ImportCSVResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, []byte) (*domain.ImportCSVResponse, error)); ok {
		return rf(ctx, userID, accountID, csvData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, []byte) *domain.ImportCSVResponse); ok {
		r0 = rf(ctx, userID, accountID, csvData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ImportCSVResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, []byte) error); ok {
		r1 = rf(ctx, userID, accountID, csvData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_ParseImportCSV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseImportCSV'
type MockTransactionService_ParseImportCSV_Call struct {
	*mock.Call
}

// ParseImportCSV is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - accountID int
//   - csvData []byte
func (_e *MockTransactionService_Expecter) ParseImportCSV(ctx interface{}, userID interface{}, accountID interface{}, csvData interface{}) *MockTransactionService_ParseImportCSV_Call {
	return &MockTransactionService_ParseImportCSV_Call{Call: _e.mock.On("ParseImportCSV", ctx, userID, accountID, csvData)}
}

func (_c *MockTransactionService_ParseImportCSV_Call) Run(run func(ctx context.Context, userID int, accountID int, csvData []byte)) *MockTransactionService_ParseImportCSV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].([]byte))
	})
	return _c
}

func (_c *MockTransactionService_ParseImportCSV_Call) Return(_a0 *domain.ImportCSVResponse, _a1 error) *MockTransactionService_ParseImportCSV_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_ParseImportCSV_Call) RunAndReturn(run func(context.Context, int, int, []byte) (*domain.ImportCSVResponse, error)) *MockTransactionService_ParseImportCSV_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, userID, period, filter
func (_m *MockTransactionService) Search(ctx context.Context, userID int, period domain.Period, filter domain.TransactionFilter) ([]*domain.Transaction, error) {
	ret := _m.Called(ctx, userID, period, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.Period, domain.TransactionFilter) ([]*domain.Transaction, error)); ok {
		return rf(ctx, userID, period, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.Period, domain.TransactionFilter) []*domain.Transaction); ok {
		r0 = rf(ctx, userID, period, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, domain.Period, domain.TransactionFilter) error); ok {
		r1 = rf(ctx, userID, period, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockTransactionService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - period domain.Period
//   - filter domain.TransactionFilter
func (_e *MockTransactionService_Expecter) Search(ctx interface{}, userID interface{}, period interface{}, filter interface{}) *MockTransactionService_Search_Call {
	return &MockTransactionService_Search_Call{Call: _e.mock.On("Search", ctx, userID, period, filter)}
}

func (_c *MockTransactionService_Search_Call) Run(run func(ctx context.Context, userID int, period domain.Period, filter domain.TransactionFilter)) *MockTransactionService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(domain.Period), args[3].(domain.TransactionFilter))
	})
	return _c
}

func (_c *MockTransactionService_Search_Call) Return(_a0 []*domain.Transaction, _a1 error) *MockTransactionService_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_Search_Call) RunAndReturn(run func(context.Context, int, domain.Period, domain.TransactionFilter) ([]*domain.Transaction, error)) *MockTransactionService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Suggestions provides a mock function with given fields: ctx, userID, filter
func (_m *MockTransactionService) Suggestions(ctx context.Context, userID int, filter domain.TransactionFilter) ([]*domain.Transaction, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for Suggestions")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.TransactionFilter) ([]*domain.Transaction, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.TransactionFilter) []*domain.Transaction); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, domain.TransactionFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_Suggestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Suggestions'
type MockTransactionService_Suggestions_Call struct {
	*mock.Call
}

// Suggestions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - filter domain.TransactionFilter
func (_e *MockTransactionService_Expecter) Suggestions(ctx interface{}, userID interface{}, filter interface{}) *MockTransactionService_Suggestions_Call {
	return &MockTransactionService_Suggestions_Call{Call: _e.mock.On("Suggestions", ctx, userID, filter)}
}

func (_c *MockTransactionService_Suggestions_Call) Run(run func(ctx context.Context, userID int, filter domain.TransactionFilter)) *MockTransactionService_Suggestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(domain.TransactionFilter))
	})
	return _c
}

func (_c *MockTransactionService_Suggestions_Call) Return(_a0 []*domain.Transaction, _a1 error) *MockTransactionService_Suggestions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_Suggestions_Call) RunAndReturn(run func(context.Context, int, domain.TransactionFilter) ([]*domain.Transaction, error)) *MockTransactionService_Suggestions_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, id, transaction
func (_m *MockTransactionService) Update(ctx context.Context, userID int, id int, transaction *domain.TransactionUpdateRequest) error {
	ret := _m.Called(ctx, userID, id, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *domain.TransactionUpdateRequest) error); ok {
		r0 = rf(ctx, userID, id, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
//   - transaction *domain.TransactionUpdateRequest
func (_e *MockTransactionService_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, transaction interface{}) *MockTransactionService_Update_Call {
	return &MockTransactionService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, transaction)}
}

func (_c *MockTransactionService_Update_Call) Run(run func(ctx context.Context, userID int, id int, transaction *domain.TransactionUpdateRequest)) *MockTransactionService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(*domain.TransactionUpdateRequest))
	})
	return _c
}

func (_c *MockTransactionService_Update_Call) Return(_a0 error) *MockTransactionService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionService_Update_Call) RunAndReturn(run func(context.Context, int, int, *domain.TransactionUpdateRequest) error) *MockTransactionService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
