// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function with given fields: ctx, id
func (_m *MockAccountRepository) Activate(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockAccountRepository_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockAccountRepository_Expecter) Activate(ctx interface{}, id interface{}) *MockAccountRepository_Activate_Call {
	return &MockAccountRepository_Activate_Call{Call: _e.mock.On("Activate", ctx, id)}
}

func (_c *MockAccountRepository_Activate_Call) Run(run func(ctx context.Context, id int)) *MockAccountRepository_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAccountRepository_Activate_Call) Return(_a0 error) *MockAccountRepository_Activate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_Activate_Call) RunAndReturn(run func(context.Context, int) error) *MockAccountRepository_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, account
func (_m *MockAccountRepository) Create(ctx context.Context, account *domain.Account) (*domain.Account, error) {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Account) (*domain.Account, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Account) *domain.Account); ok {
		r0 = rf(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Account) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - account *domain.Account
func (_e *MockAccountRepository_Expecter) Create(ctx interface{}, account interface{}) *MockAccountRepository_Create_Call {
	return &MockAccountRepository_Create_Call{Call: _e.mock.On("Create", ctx, account)}
}

func (_c *MockAccountRepository_Create_Call) Run(run func(ctx context.Context, account *domain.Account)) *MockAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Account))
	})
	return _c
}

func (_c *MockAccountRepository_Create_Call) Return(_a0 *domain.Account, _a1 error) *MockAccountRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Account) (*domain.Account, error)) *MockAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function with given fields: ctx, id
func (_m *MockAccountRepository) Deactivate(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockAccountRepository_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockAccountRepository_Expecter) Deactivate(ctx interface{}, id interface{}) *MockAccountRepository_Deactivate_Call {
	return &MockAccountRepository_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, id)}
}

func (_c *MockAccountRepository_Deactivate_Call) Run(run func(ctx context.Context, id int)) *MockAccountRepository_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAccountRepository_Deactivate_Call) Return(_a0 error) *MockAccountRepository_Deactivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_Deactivate_Call) RunAndReturn(run func(context.Context, int) error) *MockAccountRepository_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAccountRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockAccountRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAccountRepository_Delete_Call {
	return &MockAccountRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAccountRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockAccountRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAccountRepository_Delete_Call) Return(_a0 error) *MockAccountRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockAccountRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockAccountRepository) GetByID(ctx context.Context, id int) (*domain.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAccountRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockAccountRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAccountRepository_GetByID_Call {
	return &MockAccountRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAccountRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockAccountRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAccountRepository_GetByID_Call) Return(_a0 *domain.Account, _a1 error) *MockAccountRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepository_GetByID_Call) RunAndReturn(run func(context.Context, int) (*domain.Account, error)) *MockAccountRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAccountRepository) GetByUserID(ctx context.Context, userID int) ([]*domain.Account, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Account, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Account); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockAccountRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockAccountRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockAccountRepository_GetByUserID_Call {
	return &MockAccountRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockAccountRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockAccountRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAccountRepository_GetByUserID_Call) Return(_a0 []*domain.Account, _a1 error) *MockAccountRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, int) ([]*domain.Account, error)) *MockAccountRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSharedAccounts provides a mock function with given fields: ctx, userID
func (_m *MockAccountRepository) GetSharedAccounts(ctx context.Context, userID int) ([]*domain.Account, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSharedAccounts")
	}

	var r0 []*domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Account, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Account); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepository_GetSharedAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSharedAccounts'
type MockAccountRepository_GetSharedAccounts_Call struct {
	*mock.Call
}

// GetSharedAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockAccountRepository_Expecter) GetSharedAccounts(ctx interface{}, userID interface{}) *MockAccountRepository_GetSharedAccounts_Call {
	return &MockAccountRepository_GetSharedAccounts_Call{Call: _e.mock.On("GetSharedAccounts", ctx, userID)}
}

func (_c *MockAccountRepository_GetSharedAccounts_Call) Run(run func(ctx context.Context, userID int)) *MockAccountRepository_GetSharedAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAccountRepository_GetSharedAccounts_Call) Return(_a0 []*domain.Account, _a1 error) *MockAccountRepository_GetSharedAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepository_GetSharedAccounts_Call) RunAndReturn(run func(context.Context, int) ([]*domain.Account, error)) *MockAccountRepository_GetSharedAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, options
func (_m *MockAccountRepository) Search(ctx context.Context, options domain.AccountSearchOptions) ([]*domain.Account, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AccountSearchOptions) ([]*domain.Account, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AccountSearchOptions) []*domain.Account); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AccountSearchOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockAccountRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - options domain.AccountSearchOptions
func (_e *MockAccountRepository_Expecter) Search(ctx interface{}, options interface{}) *MockAccountRepository_Search_Call {
	return &MockAccountRepository_Search_Call{Call: _e.mock.On("Search", ctx, options)}
}

func (_c *MockAccountRepository_Search_Call) Run(run func(ctx context.Context, options domain.AccountSearchOptions)) *MockAccountRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AccountSearchOptions))
	})
	return _c
}

func (_c *MockAccountRepository_Search_Call) Return(_a0 []*domain.Account, _a1 error) *MockAccountRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepository_Search_Call) RunAndReturn(run func(context.Context, domain.AccountSearchOptions) ([]*domain.Account, error)) *MockAccountRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, account
func (_m *MockAccountRepository) Update(ctx context.Context, account *domain.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - account *domain.Account
func (_e *MockAccountRepository_Expecter) Update(ctx interface{}, account interface{}) *MockAccountRepository_Update_Call {
	return &MockAccountRepository_Update_Call{Call: _e.mock.On("Update", ctx, account)}
}

func (_c *MockAccountRepository_Update_Call) Run(run func(ctx context.Context, account *domain.Account)) *MockAccountRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Account))
	})
	return _c
}

func (_c *MockAccountRepository_Update_Call) Return(_a0 error) *MockAccountRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Account) error) *MockAccountRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
