// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionRecurrenceRepository is an autogenerated mock type for the TransactionRecurrenceRepository type
type MockTransactionRecurrenceRepository struct {
	mock.Mock
}

type MockTransactionRecurrenceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRecurrenceRepository) EXPECT() *MockTransactionRecurrenceRepository_Expecter {
	return &MockTransactionRecurrenceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, recurrence
func (_m *MockTransactionRecurrenceRepository) Create(ctx context.Context, recurrence *domain.TransactionRecurrence) (*domain.TransactionRecurrence, error) {
	ret := _m.Called(ctx, recurrence)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.TransactionRecurrence
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransactionRecurrence) (*domain.TransactionRecurrence, error)); ok {
		return rf(ctx, recurrence)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransactionRecurrence) *domain.TransactionRecurrence); ok {
		r0 = rf(ctx, recurrence)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransactionRecurrence)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.TransactionRecurrence) error); ok {
		r1 = rf(ctx, recurrence)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRecurrenceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRecurrenceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - recurrence *domain.TransactionRecurrence
func (_e *MockTransactionRecurrenceRepository_Expecter) Create(ctx interface{}, recurrence interface{}) *MockTransactionRecurrenceRepository_Create_Call {
	return &MockTransactionRecurrenceRepository_Create_Call{Call: _e.mock.On("Create", ctx, recurrence)}
}

func (_c *MockTransactionRecurrenceRepository_Create_Call) Run(run func(ctx context.Context, recurrence *domain.TransactionRecurrence)) *MockTransactionRecurrenceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.TransactionRecurrence))
	})
	return _c
}

func (_c *MockTransactionRecurrenceRepository_Create_Call) Return(_a0 *domain.TransactionRecurrence, _a1 error) *MockTransactionRecurrenceRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRecurrenceRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.TransactionRecurrence) (*domain.TransactionRecurrence, error)) *MockTransactionRecurrenceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockTransactionRecurrenceRepository) Delete(ctx context.Context, ids []int) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRecurrenceRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionRecurrenceRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockTransactionRecurrenceRepository_Expecter) Delete(ctx interface{}, ids interface{}) *MockTransactionRecurrenceRepository_Delete_Call {
	return &MockTransactionRecurrenceRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockTransactionRecurrenceRepository_Delete_Call) Run(run func(ctx context.Context, ids []int)) *MockTransactionRecurrenceRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int))
	})
	return _c
}

func (_c *MockTransactionRecurrenceRepository_Delete_Call) Return(_a0 error) *MockTransactionRecurrenceRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRecurrenceRepository_Delete_Call) RunAndReturn(run func(context.Context, []int) error) *MockTransactionRecurrenceRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, filter
func (_m *MockTransactionRecurrenceRepository) Search(ctx context.Context, filter domain.TransactionRecurrenceFilter) ([]*domain.TransactionRecurrence, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.TransactionRecurrence
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransactionRecurrenceFilter) ([]*domain.TransactionRecurrence, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransactionRecurrenceFilter) []*domain.TransactionRecurrence); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TransactionRecurrence)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TransactionRecurrenceFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRecurrenceRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockTransactionRecurrenceRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.TransactionRecurrenceFilter
func (_e *MockTransactionRecurrenceRepository_Expecter) Search(ctx interface{}, filter interface{}) *MockTransactionRecurrenceRepository_Search_Call {
	return &MockTransactionRecurrenceRepository_Search_Call{Call: _e.mock.On("Search", ctx, filter)}
}

func (_c *MockTransactionRecurrenceRepository_Search_Call) Run(run func(ctx context.Context, filter domain.TransactionRecurrenceFilter)) *MockTransactionRecurrenceRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TransactionRecurrenceFilter))
	})
	return _c
}

func (_c *MockTransactionRecurrenceRepository_Search_Call) Return(_a0 []*domain.TransactionRecurrence, _a1 error) *MockTransactionRecurrenceRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRecurrenceRepository_Search_Call) RunAndReturn(run func(context.Context, domain.TransactionRecurrenceFilter) ([]*domain.TransactionRecurrence, error)) *MockTransactionRecurrenceRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, recurrence
func (_m *MockTransactionRecurrenceRepository) Update(ctx context.Context, recurrence *domain.TransactionRecurrence) error {
	ret := _m.Called(ctx, recurrence)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransactionRecurrence) error); ok {
		r0 = rf(ctx, recurrence)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRecurrenceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionRecurrenceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - recurrence *domain.TransactionRecurrence
func (_e *MockTransactionRecurrenceRepository_Expecter) Update(ctx interface{}, recurrence interface{}) *MockTransactionRecurrenceRepository_Update_Call {
	return &MockTransactionRecurrenceRepository_Update_Call{Call: _e.mock.On("Update", ctx, recurrence)}
}

func (_c *MockTransactionRecurrenceRepository_Update_Call) Run(run func(ctx context.Context, recurrence *domain.TransactionRecurrence)) *MockTransactionRecurrenceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.TransactionRecurrence))
	})
	return _c
}

func (_c *MockTransactionRecurrenceRepository_Update_Call) Return(_a0 error) *MockTransactionRecurrenceRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRecurrenceRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.TransactionRecurrence) error) *MockTransactionRecurrenceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRecurrenceRepository creates a new instance of MockTransactionRecurrenceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRecurrenceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRecurrenceRepository {
	mock := &MockTransactionRecurrenceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
