// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockPushSubscriptionService is an autogenerated mock type for the PushSubscriptionService type
type MockPushSubscriptionService struct {
	mock.Mock
}

type MockPushSubscriptionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPushSubscriptionService) EXPECT() *MockPushSubscriptionService_Expecter {
	return &MockPushSubscriptionService_Expecter{mock: &_m.Mock}
}

// Status provides a mock function with given fields: ctx, userID, endpoint
func (_m *MockPushSubscriptionService) Status(ctx context.Context, userID int, endpoint string) (*domain.PushSubscriptionStatusResponse, error) {
	ret := _m.Called(ctx, userID, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *domain.PushSubscriptionStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (*domain.PushSubscriptionStatusResponse, error)); ok {
		return rf(ctx, userID, endpoint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) *domain.PushSubscriptionStatusResponse); ok {
		r0 = rf(ctx, userID, endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PushSubscriptionStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, userID, endpoint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPushSubscriptionService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockPushSubscriptionService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - endpoint string
func (_e *MockPushSubscriptionService_Expecter) Status(ctx interface{}, userID interface{}, endpoint interface{}) *MockPushSubscriptionService_Status_Call {
	return &MockPushSubscriptionService_Status_Call{Call: _e.mock.On("Status", ctx, userID, endpoint)}
}

func (_c *MockPushSubscriptionService_Status_Call) Run(run func(ctx context.Context, userID int, endpoint string)) *MockPushSubscriptionService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockPushSubscriptionService_Status_Call) Return(_a0 *domain.PushSubscriptionStatusResponse, _a1 error) *MockPushSubscriptionService_Status_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPushSubscriptionService_Status_Call) RunAndReturn(run func(context.Context, int, string) (*domain.PushSubscriptionStatusResponse, error)) *MockPushSubscriptionService_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, userID, req
func (_m *MockPushSubscriptionService) Subscribe(ctx context.Context, userID int, req *domain.SubscribePushRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.SubscribePushRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPushSubscriptionService_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockPushSubscriptionService_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - req *domain.SubscribePushRequest
func (_e *MockPushSubscriptionService_Expecter) Subscribe(ctx interface{}, userID interface{}, req interface{}) *MockPushSubscriptionService_Subscribe_Call {
	return &MockPushSubscriptionService_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, userID, req)}
}

func (_c *MockPushSubscriptionService_Subscribe_Call) Run(run func(ctx context.Context, userID int, req *domain.SubscribePushRequest)) *MockPushSubscriptionService_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.SubscribePushRequest))
	})
	return _c
}

func (_c *MockPushSubscriptionService_Subscribe_Call) Return(_a0 error) *MockPushSubscriptionService_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPushSubscriptionService_Subscribe_Call) RunAndReturn(run func(context.Context, int, *domain.SubscribePushRequest) error) *MockPushSubscriptionService_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with given fields: ctx, userID, endpoint
func (_m *MockPushSubscriptionService) Unsubscribe(ctx context.Context, userID int, endpoint string) error {
	ret := _m.Called(ctx, userID, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, userID, endpoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPushSubscriptionService_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockPushSubscriptionService_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - endpoint string
func (_e *MockPushSubscriptionService_Expecter) Unsubscribe(ctx interface{}, userID interface{}, endpoint interface{}) *MockPushSubscriptionService_Unsubscribe_Call {
	return &MockPushSubscriptionService_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", ctx, userID, endpoint)}
}

func (_c *MockPushSubscriptionService_Unsubscribe_Call) Run(run func(ctx context.Context, userID int, endpoint string)) *MockPushSubscriptionService_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockPushSubscriptionService_Unsubscribe_Call) Return(_a0 error) *MockPushSubscriptionService_Unsubscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPushSubscriptionService_Unsubscribe_Call) RunAndReturn(run func(context.Context, int, string) error) *MockPushSubscriptionService_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPushSubscriptionService creates a new instance of MockPushSubscriptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPushSubscriptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPushSubscriptionService {
	mock := &MockPushSubscriptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
