// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockNotificationService is an autogenerated mock type for the NotificationService type
type MockNotificationService struct {
	mock.Mock
}

type MockNotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationService) EXPECT() *MockNotificationService_Expecter {
	return &MockNotificationService_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function with given fields: ctx, events
func (_m *MockNotificationService) Dispatch(ctx context.Context, events []domain.NotificationEvent) {
	_m.Called(ctx, events)
}

// MockNotificationService_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockNotificationService_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - events []domain.NotificationEvent
func (_e *MockNotificationService_Expecter) Dispatch(ctx interface{}, events interface{}) *MockNotificationService_Dispatch_Call {
	return &MockNotificationService_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, events)}
}

func (_c *MockNotificationService_Dispatch_Call) Run(run func(ctx context.Context, events []domain.NotificationEvent)) *MockNotificationService_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.NotificationEvent))
	})
	return _c
}

func (_c *MockNotificationService_Dispatch_Call) Return() *MockNotificationService_Dispatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotificationService_Dispatch_Call) RunAndReturn(run func(context.Context, []domain.NotificationEvent)) *MockNotificationService_Dispatch_Call {
	_c.Run(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, filter
func (_m *MockNotificationService) List(ctx context.Context, userID int, filter domain.NotificationFilter) (*domain.NotificationListResult, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.NotificationListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.NotificationFilter) (*domain.NotificationListResult, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.NotificationFilter) *domain.NotificationListResult); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotificationListResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, domain.NotificationFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockNotificationService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - filter domain.NotificationFilter
func (_e *MockNotificationService_Expecter) List(ctx interface{}, userID interface{}, filter interface{}) *MockNotificationService_List_Call {
	return &MockNotificationService_List_Call{Call: _e.mock.On("List", ctx, userID, filter)}
}

func (_c *MockNotificationService_List_Call) Run(run func(ctx context.Context, userID int, filter domain.NotificationFilter)) *MockNotificationService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(domain.NotificationFilter))
	})
	return _c
}

func (_c *MockNotificationService_List_Call) Return(_a0 *domain.NotificationListResult, _a1 error) *MockNotificationService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationService_List_Call) RunAndReturn(run func(context.Context, int, domain.NotificationFilter) (*domain.NotificationListResult, error)) *MockNotificationService_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function with given fields: ctx, userID
func (_m *MockNotificationService) MarkAllRead(ctx context.Context, userID int) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationService_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type MockNotificationService_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockNotificationService_Expecter) MarkAllRead(ctx interface{}, userID interface{}) *MockNotificationService_MarkAllRead_Call {
	return &MockNotificationService_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userID)}
}

func (_c *MockNotificationService_MarkAllRead_Call) Run(run func(ctx context.Context, userID int)) *MockNotificationService_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockNotificationService_MarkAllRead_Call) Return(_a0 error) *MockNotificationService_MarkAllRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationService_MarkAllRead_Call) RunAndReturn(run func(context.Context, int) error) *MockNotificationService_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function with given fields: ctx, userID, notificationID
func (_m *MockNotificationService) MarkRead(ctx context.Context, userID int, notificationID int) error {
	ret := _m.Called(ctx, userID, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, notificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationService_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockNotificationService_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - notificationID int
func (_e *MockNotificationService_Expecter) MarkRead(ctx interface{}, userID interface{}, notificationID interface{}) *MockNotificationService_MarkRead_Call {
	return &MockNotificationService_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, userID, notificationID)}
}

func (_c *MockNotificationService_MarkRead_Call) Run(run func(ctx context.Context, userID int, notificationID int)) *MockNotificationService_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockNotificationService_MarkRead_Call) Return(_a0 error) *MockNotificationService_MarkRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationService_MarkRead_Call) RunAndReturn(run func(context.Context, int, int) error) *MockNotificationService_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// UnreadCount provides a mock function with given fields: ctx, userID
func (_m *MockNotificationService) UnreadCount(ctx context.Context, userID int) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnreadCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationService_UnreadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnreadCount'
type MockNotificationService_UnreadCount_Call struct {
	*mock.Call
}

// UnreadCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockNotificationService_Expecter) UnreadCount(ctx interface{}, userID interface{}) *MockNotificationService_UnreadCount_Call {
	return &MockNotificationService_UnreadCount_Call{Call: _e.mock.On("UnreadCount", ctx, userID)}
}

func (_c *MockNotificationService_UnreadCount_Call) Run(run func(ctx context.Context, userID int)) *MockNotificationService_UnreadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockNotificationService_UnreadCount_Call) Return(_a0 int64, _a1 error) *MockNotificationService_UnreadCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationService_UnreadCount_Call) RunAndReturn(run func(context.Context, int) (int64, error)) *MockNotificationService_UnreadCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationService creates a new instance of MockNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationService {
	mock := &MockNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
