// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionService is an autogenerated mock type for the TransactionService type
type MockTransactionService struct {
	mock.Mock
}

type MockTransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionService) EXPECT() *MockTransactionService_Expecter {
	return &MockTransactionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, transaction
func (_m *MockTransactionService) Create(ctx context.Context, userID int, transaction *domain.TransactionCreateRequest) error {
	ret := _m.Called(ctx, userID, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.TransactionCreateRequest) error); ok {
		r0 = rf(ctx, userID, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - transaction *domain.TransactionCreateRequest
func (_e *MockTransactionService_Expecter) Create(ctx interface{}, userID interface{}, transaction interface{}) *MockTransactionService_Create_Call {
	return &MockTransactionService_Create_Call{Call: _e.mock.On("Create", ctx, userID, transaction)}
}

func (_c *MockTransactionService_Create_Call) Run(run func(ctx context.Context, userID int, transaction *domain.TransactionCreateRequest)) *MockTransactionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.TransactionCreateRequest))
	})
	return _c
}

func (_c *MockTransactionService_Create_Call) Return(_a0 error) *MockTransactionService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionService_Create_Call) RunAndReturn(run func(context.Context, int, *domain.TransactionCreateRequest) error) *MockTransactionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
