// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUserConnectionService is an autogenerated mock type for the UserConnectionService type
type MockUserConnectionService struct {
	mock.Mock
}

type MockUserConnectionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserConnectionService) EXPECT() *MockUserConnectionService_Expecter {
	return &MockUserConnectionService_Expecter{mock: &_m.Mock}
}

// AcceptInviteByExternalID provides a mock function with given fields: ctx, currentUserID, inviterExternalID, fromDefaultSplitPercentage
func (_m *MockUserConnectionService) AcceptInviteByExternalID(ctx context.Context, currentUserID int, inviterExternalID string, fromDefaultSplitPercentage int) (*domain.UserConnection, error) {
	ret := _m.Called(ctx, currentUserID, inviterExternalID, fromDefaultSplitPercentage)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInviteByExternalID")
	}

	var r0 *domain.UserConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, int) (*domain.UserConnection, error)); ok {
		return rf(ctx, currentUserID, inviterExternalID, fromDefaultSplitPercentage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, int) *domain.UserConnection); ok {
		r0 = rf(ctx, currentUserID, inviterExternalID, fromDefaultSplitPercentage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, int) error); ok {
		r1 = rf(ctx, currentUserID, inviterExternalID, fromDefaultSplitPercentage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserConnectionService_AcceptInviteByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInviteByExternalID'
type MockUserConnectionService_AcceptInviteByExternalID_Call struct {
	*mock.Call
}

// AcceptInviteByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - currentUserID int
//   - inviterExternalID string
//   - fromDefaultSplitPercentage int
func (_e *MockUserConnectionService_Expecter) AcceptInviteByExternalID(ctx interface{}, currentUserID interface{}, inviterExternalID interface{}, fromDefaultSplitPercentage interface{}) *MockUserConnectionService_AcceptInviteByExternalID_Call {
	return &MockUserConnectionService_AcceptInviteByExternalID_Call{Call: _e.mock.On("AcceptInviteByExternalID", ctx, currentUserID, inviterExternalID, fromDefaultSplitPercentage)}
}

func (_c *MockUserConnectionService_AcceptInviteByExternalID_Call) Run(run func(ctx context.Context, currentUserID int, inviterExternalID string, fromDefaultSplitPercentage int)) *MockUserConnectionService_AcceptInviteByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockUserConnectionService_AcceptInviteByExternalID_Call) Return(_a0 *domain.UserConnection, _a1 error) *MockUserConnectionService_AcceptInviteByExternalID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserConnectionService_AcceptInviteByExternalID_Call) RunAndReturn(run func(context.Context, int, string, int) (*domain.UserConnection, error)) *MockUserConnectionService_AcceptInviteByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, fromUserID, toUserID, fromDefaultSplitPercentage
func (_m *MockUserConnectionService) Create(ctx context.Context, fromUserID int, toUserID int, fromDefaultSplitPercentage int) (*domain.UserConnection, error) {
	ret := _m.Called(ctx, fromUserID, toUserID, fromDefaultSplitPercentage)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.UserConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) (*domain.UserConnection, error)); ok {
		return rf(ctx, fromUserID, toUserID, fromDefaultSplitPercentage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) *domain.UserConnection); ok {
		r0 = rf(ctx, fromUserID, toUserID, fromDefaultSplitPercentage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, fromUserID, toUserID, fromDefaultSplitPercentage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserConnectionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserConnectionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - fromUserID int
//   - toUserID int
//   - fromDefaultSplitPercentage int
func (_e *MockUserConnectionService_Expecter) Create(ctx interface{}, fromUserID interface{}, toUserID interface{}, fromDefaultSplitPercentage interface{}) *MockUserConnectionService_Create_Call {
	return &MockUserConnectionService_Create_Call{Call: _e.mock.On("Create", ctx, fromUserID, toUserID, fromDefaultSplitPercentage)}
}

func (_c *MockUserConnectionService_Create_Call) Run(run func(ctx context.Context, fromUserID int, toUserID int, fromDefaultSplitPercentage int)) *MockUserConnectionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockUserConnectionService_Create_Call) Return(_a0 *domain.UserConnection, _a1 error) *MockUserConnectionService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserConnectionService_Create_Call) RunAndReturn(run func(context.Context, int, int, int) (*domain.UserConnection, error)) *MockUserConnectionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *MockUserConnectionService) Delete(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserConnectionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserConnectionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockUserConnectionService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockUserConnectionService_Delete_Call {
	return &MockUserConnectionService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockUserConnectionService_Delete_Call) Run(run func(ctx context.Context, userID int, id int)) *MockUserConnectionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockUserConnectionService_Delete_Call) Return(_a0 error) *MockUserConnectionService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserConnectionService_Delete_Call) RunAndReturn(run func(context.Context, int, int) error) *MockUserConnectionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, options
func (_m *MockUserConnectionService) Search(ctx context.Context, options domain.UserConnectionSearchOptions) ([]*domain.UserConnection, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.UserConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserConnectionSearchOptions) ([]*domain.UserConnection, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserConnectionSearchOptions) []*domain.UserConnection); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserConnectionSearchOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserConnectionService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockUserConnectionService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - options domain.UserConnectionSearchOptions
func (_e *MockUserConnectionService_Expecter) Search(ctx interface{}, options interface{}) *MockUserConnectionService_Search_Call {
	return &MockUserConnectionService_Search_Call{Call: _e.mock.On("Search", ctx, options)}
}

func (_c *MockUserConnectionService_Search_Call) Run(run func(ctx context.Context, options domain.UserConnectionSearchOptions)) *MockUserConnectionService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserConnectionSearchOptions))
	})
	return _c
}

func (_c *MockUserConnectionService_Search_Call) Return(_a0 []*domain.UserConnection, _a1 error) *MockUserConnectionService_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserConnectionService_Search_Call) RunAndReturn(run func(context.Context, domain.UserConnectionSearchOptions) ([]*domain.UserConnection, error)) *MockUserConnectionService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchOne provides a mock function with given fields: ctx, options
func (_m *MockUserConnectionService) SearchOne(ctx context.Context, options domain.UserConnectionSearchOptions) (*domain.UserConnection, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for SearchOne")
	}

	var r0 *domain.UserConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserConnectionSearchOptions) (*domain.UserConnection, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserConnectionSearchOptions) *domain.UserConnection); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserConnectionSearchOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserConnectionService_SearchOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchOne'
type MockUserConnectionService_SearchOne_Call struct {
	*mock.Call
}

// SearchOne is a helper method to define mock.On call
//   - ctx context.Context
//   - options domain.UserConnectionSearchOptions
func (_e *MockUserConnectionService_Expecter) SearchOne(ctx interface{}, options interface{}) *MockUserConnectionService_SearchOne_Call {
	return &MockUserConnectionService_SearchOne_Call{Call: _e.mock.On("SearchOne", ctx, options)}
}

func (_c *MockUserConnectionService_SearchOne_Call) Run(run func(ctx context.Context, options domain.UserConnectionSearchOptions)) *MockUserConnectionService_SearchOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserConnectionSearchOptions))
	})
	return _c
}

func (_c *MockUserConnectionService_SearchOne_Call) Return(_a0 *domain.UserConnection, _a1 error) *MockUserConnectionService_SearchOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserConnectionService_SearchOne_Call) RunAndReturn(run func(context.Context, domain.UserConnectionSearchOptions) (*domain.UserConnection, error)) *MockUserConnectionService_SearchOne_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, userID, id, status
func (_m *MockUserConnectionService) UpdateStatus(ctx context.Context, userID int, id int, status domain.UserConnectionStatusEnum) error {
	ret := _m.Called(ctx, userID, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, domain.UserConnectionStatusEnum) error); ok {
		r0 = rf(ctx, userID, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserConnectionService_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockUserConnectionService_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
//   - status domain.UserConnectionStatusEnum
func (_e *MockUserConnectionService_Expecter) UpdateStatus(ctx interface{}, userID interface{}, id interface{}, status interface{}) *MockUserConnectionService_UpdateStatus_Call {
	return &MockUserConnectionService_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, userID, id, status)}
}

func (_c *MockUserConnectionService_UpdateStatus_Call) Run(run func(ctx context.Context, userID int, id int, status domain.UserConnectionStatusEnum)) *MockUserConnectionService_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(domain.UserConnectionStatusEnum))
	})
	return _c
}

func (_c *MockUserConnectionService_UpdateStatus_Call) Return(_a0 error) *MockUserConnectionService_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserConnectionService_UpdateStatus_Call) RunAndReturn(run func(context.Context, int, int, domain.UserConnectionStatusEnum) error) *MockUserConnectionService_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserConnectionService creates a new instance of MockUserConnectionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserConnectionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserConnectionService {
	mock := &MockUserConnectionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
