// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionTemplateService is an autogenerated mock type for the TransactionTemplateService type
type MockTransactionTemplateService struct {
	mock.Mock
}

type MockTransactionTemplateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionTemplateService) EXPECT() *MockTransactionTemplateService_Expecter {
	return &MockTransactionTemplateService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, name, payload
func (_m *MockTransactionTemplateService) Create(ctx context.Context, userID int, name string, payload domain.TransactionTemplatePayload) (*domain.TransactionTemplate, error) {
	ret := _m.Called(ctx, userID, name, payload)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.TransactionTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, domain.TransactionTemplatePayload) (*domain.TransactionTemplate, error)); ok {
		return rf(ctx, userID, name, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, domain.TransactionTemplatePayload) *domain.TransactionTemplate); ok {
		r0 = rf(ctx, userID, name, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransactionTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, domain.TransactionTemplatePayload) error); ok {
		r1 = rf(ctx, userID, name, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionTemplateService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionTemplateService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - name string
//   - payload domain.TransactionTemplatePayload
func (_e *MockTransactionTemplateService_Expecter) Create(ctx interface{}, userID interface{}, name interface{}, payload interface{}) *MockTransactionTemplateService_Create_Call {
	return &MockTransactionTemplateService_Create_Call{Call: _e.mock.On("Create", ctx, userID, name, payload)}
}

func (_c *MockTransactionTemplateService_Create_Call) Run(run func(ctx context.Context, userID int, name string, payload domain.TransactionTemplatePayload)) *MockTransactionTemplateService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(domain.TransactionTemplatePayload))
	})
	return _c
}

func (_c *MockTransactionTemplateService_Create_Call) Return(_a0 *domain.TransactionTemplate, _a1 error) *MockTransactionTemplateService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionTemplateService_Create_Call) RunAndReturn(run func(context.Context, int, string, domain.TransactionTemplatePayload) (*domain.TransactionTemplate, error)) *MockTransactionTemplateService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *MockTransactionTemplateService) Delete(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionTemplateService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionTemplateService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockTransactionTemplateService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockTransactionTemplateService_Delete_Call {
	return &MockTransactionTemplateService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockTransactionTemplateService_Delete_Call) Run(run func(ctx context.Context, userID int, id int)) *MockTransactionTemplateService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionTemplateService_Delete_Call) Return(_a0 error) *MockTransactionTemplateService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionTemplateService_Delete_Call) RunAndReturn(run func(context.Context, int, int) error) *MockTransactionTemplateService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID
func (_m *MockTransactionTemplateService) List(ctx context.Context, userID int) ([]*domain.TransactionTemplate, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.TransactionTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.TransactionTemplate, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.TransactionTemplate); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TransactionTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionTemplateService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTransactionTemplateService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockTransactionTemplateService_Expecter) List(ctx interface{}, userID interface{}) *MockTransactionTemplateService_List_Call {
	return &MockTransactionTemplateService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockTransactionTemplateService_List_Call) Run(run func(ctx context.Context, userID int)) *MockTransactionTemplateService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionTemplateService_List_Call) Return(_a0 []*domain.TransactionTemplate, _a1 error) *MockTransactionTemplateService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionTemplateService_List_Call) RunAndReturn(run func(context.Context, int) ([]*domain.TransactionTemplate, error)) *MockTransactionTemplateService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, id, name, payload
func (_m *MockTransactionTemplateService) Update(ctx context.Context, userID int, id int, name string, payload domain.TransactionTemplatePayload) error {
	ret := _m.Called(ctx, userID, id, name, payload)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, domain.TransactionTemplatePayload) error); ok {
		r0 = rf(ctx, userID, id, name, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionTemplateService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionTemplateService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
//   - name string
//   - payload domain.TransactionTemplatePayload
func (_e *MockTransactionTemplateService_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, name interface{}, payload interface{}) *MockTransactionTemplateService_Update_Call {
	return &MockTransactionTemplateService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, name, payload)}
}

func (_c *MockTransactionTemplateService_Update_Call) Run(run func(ctx context.Context, userID int, id int, name string, payload domain.TransactionTemplatePayload)) *MockTransactionTemplateService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string), args[4].(domain.TransactionTemplatePayload))
	})
	return _c
}

func (_c *MockTransactionTemplateService_Update_Call) Return(_a0 error) *MockTransactionTemplateService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionTemplateService_Update_Call) RunAndReturn(run func(context.Context, int, int, string, domain.TransactionTemplatePayload) error) *MockTransactionTemplateService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionTemplateService creates a new instance of MockTransactionTemplateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionTemplateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionTemplateService {
	mock := &MockTransactionTemplateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
