// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	domain "github.com/finance_app/backend/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactionService is an autogenerated mock type for the TransactionService type
type MockTransactionService struct {
	mock.Mock
}

type MockTransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionService) EXPECT() *MockTransactionService_Expecter {
	return &MockTransactionService_Expecter{mock: &_m.Mock}
}

// BulkUpdate provides a mock function with given fields: ctx, userID, updates
func (_m *MockTransactionService) BulkUpdate(ctx context.Context, userID int, updates domain.BulkUpdateTransaction) error {
	ret := _m.Called(ctx, userID, updates)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.BulkUpdateTransaction) error); ok {
		r0 = rf(ctx, userID, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionService_BulkUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpdate'
type MockTransactionService_BulkUpdate_Call struct {
	*mock.Call
}

// BulkUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - updates domain.BulkUpdateTransaction
func (_e *MockTransactionService_Expecter) BulkUpdate(ctx interface{}, userID interface{}, updates interface{}) *MockTransactionService_BulkUpdate_Call {
	return &MockTransactionService_BulkUpdate_Call{Call: _e.mock.On("BulkUpdate", ctx, userID, updates)}
}

func (_c *MockTransactionService_BulkUpdate_Call) Run(run func(ctx context.Context, userID int, updates domain.BulkUpdateTransaction)) *MockTransactionService_BulkUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(domain.BulkUpdateTransaction))
	})
	return _c
}

func (_c *MockTransactionService_BulkUpdate_Call) Return(_a0 error) *MockTransactionService_BulkUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionService_BulkUpdate_Call) RunAndReturn(run func(context.Context, int, domain.BulkUpdateTransaction) error) *MockTransactionService_BulkUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userID, transaction
func (_m *MockTransactionService) Create(ctx context.Context, userID int, transaction *domain.Transaction) (*domain.Transaction, error) {
	ret := _m.Called(ctx, userID, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Transaction) (*domain.Transaction, error)); ok {
		return rf(ctx, userID, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Transaction) *domain.Transaction); ok {
		r0 = rf(ctx, userID, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *domain.Transaction) error); ok {
		r1 = rf(ctx, userID, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - transaction *domain.Transaction
func (_e *MockTransactionService_Expecter) Create(ctx interface{}, userID interface{}, transaction interface{}) *MockTransactionService_Create_Call {
	return &MockTransactionService_Create_Call{Call: _e.mock.On("Create", ctx, userID, transaction)}
}

func (_c *MockTransactionService_Create_Call) Run(run func(ctx context.Context, userID int, transaction *domain.Transaction)) *MockTransactionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Transaction))
	})
	return _c
}

func (_c *MockTransactionService_Create_Call) Return(_a0 *domain.Transaction, _a1 error) *MockTransactionService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_Create_Call) RunAndReturn(run func(context.Context, int, *domain.Transaction) (*domain.Transaction, error)) *MockTransactionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRecurring provides a mock function with given fields: ctx, userID, transaction, config
func (_m *MockTransactionService) CreateRecurring(ctx context.Context, userID int, transaction *domain.Transaction, config domain.TransactionRecurrenceConfig) ([]*domain.Transaction, error) {
	ret := _m.Called(ctx, userID, transaction, config)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecurring")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Transaction, domain.TransactionRecurrenceConfig) ([]*domain.Transaction, error)); ok {
		return rf(ctx, userID, transaction, config)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Transaction, domain.TransactionRecurrenceConfig) []*domain.Transaction); ok {
		r0 = rf(ctx, userID, transaction, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *domain.Transaction, domain.TransactionRecurrenceConfig) error); ok {
		r1 = rf(ctx, userID, transaction, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_CreateRecurring_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRecurring'
type MockTransactionService_CreateRecurring_Call struct {
	*mock.Call
}

// CreateRecurring is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - transaction *domain.Transaction
//   - config domain.TransactionRecurrenceConfig
func (_e *MockTransactionService_Expecter) CreateRecurring(ctx interface{}, userID interface{}, transaction interface{}, config interface{}) *MockTransactionService_CreateRecurring_Call {
	return &MockTransactionService_CreateRecurring_Call{Call: _e.mock.On("CreateRecurring", ctx, userID, transaction, config)}
}

func (_c *MockTransactionService_CreateRecurring_Call) Run(run func(ctx context.Context, userID int, transaction *domain.Transaction, config domain.TransactionRecurrenceConfig)) *MockTransactionService_CreateRecurring_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Transaction), args[3].(domain.TransactionRecurrenceConfig))
	})
	return _c
}

func (_c *MockTransactionService_CreateRecurring_Call) Return(_a0 []*domain.Transaction, _a1 error) *MockTransactionService_CreateRecurring_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_CreateRecurring_Call) RunAndReturn(run func(context.Context, int, *domain.Transaction, domain.TransactionRecurrenceConfig) ([]*domain.Transaction, error)) *MockTransactionService_CreateRecurring_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *MockTransactionService) Delete(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockTransactionService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockTransactionService_Delete_Call {
	return &MockTransactionService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockTransactionService_Delete_Call) Run(run func(ctx context.Context, userID int, id int)) *MockTransactionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionService_Delete_Call) Return(_a0 error) *MockTransactionService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionService_Delete_Call) RunAndReturn(run func(context.Context, int, int) error) *MockTransactionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *MockTransactionService) GetByID(ctx context.Context, userID int, id int) (*domain.Transaction, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*domain.Transaction, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *domain.Transaction); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTransactionService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockTransactionService_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *MockTransactionService_GetByID_Call {
	return &MockTransactionService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *MockTransactionService_GetByID_Call) Run(run func(ctx context.Context, userID int, id int)) *MockTransactionService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionService_GetByID_Call) Return(_a0 *domain.Transaction, _a1 error) *MockTransactionService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_GetByID_Call) RunAndReturn(run func(context.Context, int, int) (*domain.Transaction, error)) *MockTransactionService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGrouped provides a mock function with given fields: ctx, userID, filter, groupBy
func (_m *MockTransactionService) GetGrouped(ctx context.Context, userID int, filter domain.TransactionFilter, groupBy domain.TransactionGroupBy) (map[string][]*domain.Transaction, error) {
	ret := _m.Called(ctx, userID, filter, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for GetGrouped")
	}

	var r0 map[string][]*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.TransactionFilter, domain.TransactionGroupBy) (map[string][]*domain.Transaction, error)); ok {
		return rf(ctx, userID, filter, groupBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.TransactionFilter, domain.TransactionGroupBy) map[string][]*domain.Transaction); ok {
		r0 = rf(ctx, userID, filter, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, domain.TransactionFilter, domain.TransactionGroupBy) error); ok {
		r1 = rf(ctx, userID, filter, groupBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_GetGrouped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrouped'
type MockTransactionService_GetGrouped_Call struct {
	*mock.Call
}

// GetGrouped is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - filter domain.TransactionFilter
//   - groupBy domain.TransactionGroupBy
func (_e *MockTransactionService_Expecter) GetGrouped(ctx interface{}, userID interface{}, filter interface{}, groupBy interface{}) *MockTransactionService_GetGrouped_Call {
	return &MockTransactionService_GetGrouped_Call{Call: _e.mock.On("GetGrouped", ctx, userID, filter, groupBy)}
}

func (_c *MockTransactionService_GetGrouped_Call) Run(run func(ctx context.Context, userID int, filter domain.TransactionFilter, groupBy domain.TransactionGroupBy)) *MockTransactionService_GetGrouped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(domain.TransactionFilter), args[3].(domain.TransactionGroupBy))
	})
	return _c
}

func (_c *MockTransactionService_GetGrouped_Call) Return(_a0 map[string][]*domain.Transaction, _a1 error) *MockTransactionService_GetGrouped_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_GetGrouped_Call) RunAndReturn(run func(context.Context, int, domain.TransactionFilter, domain.TransactionGroupBy) (map[string][]*domain.Transaction, error)) *MockTransactionService_GetGrouped_Call {
	_c.Call.Return(run)
	return _c
}

// ImportCSV provides a mock function with given fields: ctx, userID, reader
func (_m *MockTransactionService) ImportCSV(ctx context.Context, userID int, reader io.Reader) ([]*domain.Transaction, error) {
	ret := _m.Called(ctx, userID, reader)

	if len(ret) == 0 {
		panic("no return value specified for ImportCSV")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, io.Reader) ([]*domain.Transaction, error)); ok {
		return rf(ctx, userID, reader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, io.Reader) []*domain.Transaction); ok {
		r0 = rf(ctx, userID, reader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, io.Reader) error); ok {
		r1 = rf(ctx, userID, reader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_ImportCSV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportCSV'
type MockTransactionService_ImportCSV_Call struct {
	*mock.Call
}

// ImportCSV is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - reader io.Reader
func (_e *MockTransactionService_Expecter) ImportCSV(ctx interface{}, userID interface{}, reader interface{}) *MockTransactionService_ImportCSV_Call {
	return &MockTransactionService_ImportCSV_Call{Call: _e.mock.On("ImportCSV", ctx, userID, reader)}
}

func (_c *MockTransactionService_ImportCSV_Call) Run(run func(ctx context.Context, userID int, reader io.Reader)) *MockTransactionService_ImportCSV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(io.Reader))
	})
	return _c
}

func (_c *MockTransactionService_ImportCSV_Call) Return(_a0 []*domain.Transaction, _a1 error) *MockTransactionService_ImportCSV_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_ImportCSV_Call) RunAndReturn(run func(context.Context, int, io.Reader) ([]*domain.Transaction, error)) *MockTransactionService_ImportCSV_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, filter, orderBy, limit, offset
func (_m *MockTransactionService) List(ctx context.Context, userID int, filter domain.TransactionFilter, orderBy domain.TransactionOrderBy, limit int, offset int) ([]*domain.Transaction, int64, error) {
	ret := _m.Called(ctx, userID, filter, orderBy, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Transaction
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.TransactionFilter, domain.TransactionOrderBy, int, int) ([]*domain.Transaction, int64, error)); ok {
		return rf(ctx, userID, filter, orderBy, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.TransactionFilter, domain.TransactionOrderBy, int, int) []*domain.Transaction); ok {
		r0 = rf(ctx, userID, filter, orderBy, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, domain.TransactionFilter, domain.TransactionOrderBy, int, int) int64); ok {
		r1 = rf(ctx, userID, filter, orderBy, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, domain.TransactionFilter, domain.TransactionOrderBy, int, int) error); ok {
		r2 = rf(ctx, userID, filter, orderBy, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTransactionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTransactionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - filter domain.TransactionFilter
//   - orderBy domain.TransactionOrderBy
//   - limit int
//   - offset int
func (_e *MockTransactionService_Expecter) List(ctx interface{}, userID interface{}, filter interface{}, orderBy interface{}, limit interface{}, offset interface{}) *MockTransactionService_List_Call {
	return &MockTransactionService_List_Call{Call: _e.mock.On("List", ctx, userID, filter, orderBy, limit, offset)}
}

func (_c *MockTransactionService_List_Call) Run(run func(ctx context.Context, userID int, filter domain.TransactionFilter, orderBy domain.TransactionOrderBy, limit int, offset int)) *MockTransactionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(domain.TransactionFilter), args[3].(domain.TransactionOrderBy), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockTransactionService_List_Call) Return(_a0 []*domain.Transaction, _a1 int64, _a2 error) *MockTransactionService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTransactionService_List_Call) RunAndReturn(run func(context.Context, int, domain.TransactionFilter, domain.TransactionOrderBy, int, int) ([]*domain.Transaction, int64, error)) *MockTransactionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestCategory provides a mock function with given fields: ctx, userID, description
func (_m *MockTransactionService) SuggestCategory(ctx context.Context, userID int, description string) (*domain.Category, error) {
	ret := _m.Called(ctx, userID, description)

	if len(ret) == 0 {
		panic("no return value specified for SuggestCategory")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (*domain.Category, error)); ok {
		return rf(ctx, userID, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) *domain.Category); ok {
		r0 = rf(ctx, userID, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, userID, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_SuggestCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestCategory'
type MockTransactionService_SuggestCategory_Call struct {
	*mock.Call
}

// SuggestCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - description string
func (_e *MockTransactionService_Expecter) SuggestCategory(ctx interface{}, userID interface{}, description interface{}) *MockTransactionService_SuggestCategory_Call {
	return &MockTransactionService_SuggestCategory_Call{Call: _e.mock.On("SuggestCategory", ctx, userID, description)}
}

func (_c *MockTransactionService_SuggestCategory_Call) Run(run func(ctx context.Context, userID int, description string)) *MockTransactionService_SuggestCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockTransactionService_SuggestCategory_Call) Return(_a0 *domain.Category, _a1 error) *MockTransactionService_SuggestCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_SuggestCategory_Call) RunAndReturn(run func(context.Context, int, string) (*domain.Category, error)) *MockTransactionService_SuggestCategory_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, transaction
func (_m *MockTransactionService) Update(ctx context.Context, userID int, transaction *domain.Transaction) error {
	ret := _m.Called(ctx, userID, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Transaction) error); ok {
		r0 = rf(ctx, userID, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - transaction *domain.Transaction
func (_e *MockTransactionService_Expecter) Update(ctx interface{}, userID interface{}, transaction interface{}) *MockTransactionService_Update_Call {
	return &MockTransactionService_Update_Call{Call: _e.mock.On("Update", ctx, userID, transaction)}
}

func (_c *MockTransactionService_Update_Call) Run(run func(ctx context.Context, userID int, transaction *domain.Transaction)) *MockTransactionService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Transaction))
	})
	return _c
}

func (_c *MockTransactionService_Update_Call) Return(_a0 error) *MockTransactionService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionService_Update_Call) RunAndReturn(run func(context.Context, int, *domain.Transaction) error) *MockTransactionService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
