// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	webpush "github.com/SherClockHolmes/webpush-go"
)

// MockPushSender is an autogenerated mock type for the PushSender type
type MockPushSender struct {
	mock.Mock
}

type MockPushSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPushSender) EXPECT() *MockPushSender_Expecter {
	return &MockPushSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: payload, sub, opts
func (_m *MockPushSender) Send(payload []byte, sub *webpush.Subscription, opts *webpush.Options) (*http.Response, error) {
	ret := _m.Called(payload, sub, opts)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, *webpush.Subscription, *webpush.Options) (*http.Response, error)); ok {
		return rf(payload, sub, opts)
	}
	if rf, ok := ret.Get(0).(func([]byte, *webpush.Subscription, *webpush.Options) *http.Response); ok {
		r0 = rf(payload, sub, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, *webpush.Subscription, *webpush.Options) error); ok {
		r1 = rf(payload, sub, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPushSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockPushSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - payload []byte
//   - sub *webpush.Subscription
//   - opts *webpush.Options
func (_e *MockPushSender_Expecter) Send(payload interface{}, sub interface{}, opts interface{}) *MockPushSender_Send_Call {
	return &MockPushSender_Send_Call{Call: _e.mock.On("Send", payload, sub, opts)}
}

func (_c *MockPushSender_Send_Call) Run(run func(payload []byte, sub *webpush.Subscription, opts *webpush.Options)) *MockPushSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(*webpush.Subscription), args[2].(*webpush.Options))
	})
	return _c
}

func (_c *MockPushSender_Send_Call) Return(_a0 *http.Response, _a1 error) *MockPushSender_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPushSender_Send_Call) RunAndReturn(run func([]byte, *webpush.Subscription, *webpush.Options) (*http.Response, error)) *MockPushSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPushSender creates a new instance of MockPushSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPushSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPushSender {
	mock := &MockPushSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
