// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDBTransaction is an autogenerated mock type for the DBTransaction type
type MockDBTransaction struct {
	mock.Mock
}

type MockDBTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBTransaction) EXPECT() *MockDBTransaction_Expecter {
	return &MockDBTransaction_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *MockDBTransaction) Begin(ctx context.Context) (context.Context, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBTransaction_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockDBTransaction_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDBTransaction_Expecter) Begin(ctx interface{}) *MockDBTransaction_Begin_Call {
	return &MockDBTransaction_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockDBTransaction_Begin_Call) Run(run func(ctx context.Context)) *MockDBTransaction_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDBTransaction_Begin_Call) Return(_a0 context.Context, _a1 error) *MockDBTransaction_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBTransaction_Begin_Call) RunAndReturn(run func(context.Context) (context.Context, error)) *MockDBTransaction_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: ctx
func (_m *MockDBTransaction) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDBTransaction_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockDBTransaction_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDBTransaction_Expecter) Commit(ctx interface{}) *MockDBTransaction_Commit_Call {
	return &MockDBTransaction_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockDBTransaction_Commit_Call) Run(run func(ctx context.Context)) *MockDBTransaction_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDBTransaction_Commit_Call) Return(_a0 error) *MockDBTransaction_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBTransaction_Commit_Call) RunAndReturn(run func(context.Context) error) *MockDBTransaction_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockDBTransaction) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDBTransaction_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockDBTransaction_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDBTransaction_Expecter) Rollback(ctx interface{}) *MockDBTransaction_Rollback_Call {
	return &MockDBTransaction_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockDBTransaction_Rollback_Call) Run(run func(ctx context.Context)) *MockDBTransaction_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDBTransaction_Rollback_Call) Return(_a0 error) *MockDBTransaction_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBTransaction_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockDBTransaction_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBTransaction creates a new instance of MockDBTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBTransaction {
	mock := &MockDBTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
