// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUserSettingsRepository is an autogenerated mock type for the UserSettingsRepository type
type MockUserSettingsRepository struct {
	mock.Mock
}

type MockUserSettingsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserSettingsRepository) EXPECT() *MockUserSettingsRepository_Expecter {
	return &MockUserSettingsRepository_Expecter{mock: &_m.Mock}
}

// CreateOrUpdate provides a mock function with given fields: ctx, settings
func (_m *MockUserSettingsRepository) CreateOrUpdate(ctx context.Context, settings *domain.UserSettings) error {
	ret := _m.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserSettings) error); ok {
		r0 = rf(ctx, settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserSettingsRepository_CreateOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdate'
type MockUserSettingsRepository_CreateOrUpdate_Call struct {
	*mock.Call
}

// CreateOrUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *domain.UserSettings
func (_e *MockUserSettingsRepository_Expecter) CreateOrUpdate(ctx interface{}, settings interface{}) *MockUserSettingsRepository_CreateOrUpdate_Call {
	return &MockUserSettingsRepository_CreateOrUpdate_Call{Call: _e.mock.On("CreateOrUpdate", ctx, settings)}
}

func (_c *MockUserSettingsRepository_CreateOrUpdate_Call) Run(run func(ctx context.Context, settings *domain.UserSettings)) *MockUserSettingsRepository_CreateOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.UserSettings))
	})
	return _c
}

func (_c *MockUserSettingsRepository_CreateOrUpdate_Call) Return(_a0 error) *MockUserSettingsRepository_CreateOrUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserSettingsRepository_CreateOrUpdate_Call) RunAndReturn(run func(context.Context, *domain.UserSettings) error) *MockUserSettingsRepository_CreateOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockUserSettingsRepository) GetByUserID(ctx context.Context, userID int) (*domain.UserSettings, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *domain.UserSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.UserSettings, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.UserSettings); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserSettingsRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockUserSettingsRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserSettingsRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockUserSettingsRepository_GetByUserID_Call {
	return &MockUserSettingsRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockUserSettingsRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockUserSettingsRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserSettingsRepository_GetByUserID_Call) Return(_a0 *domain.UserSettings, _a1 error) *MockUserSettingsRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserSettingsRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, int) (*domain.UserSettings, error)) *MockUserSettingsRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserSettingsRepository creates a new instance of MockUserSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserSettingsRepository {
	mock := &MockUserSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
