// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSettlementService is an autogenerated mock type for the SettlementService type
type MockSettlementService struct {
	mock.Mock
}

type MockSettlementService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettlementService) EXPECT() *MockSettlementService_Expecter {
	return &MockSettlementService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, settlement
func (_m *MockSettlementService) Create(ctx context.Context, settlement *domain.Settlement) (*domain.Settlement, error) {
	ret := _m.Called(ctx, settlement)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Settlement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Settlement) (*domain.Settlement, error)); ok {
		return rf(ctx, settlement)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Settlement) *domain.Settlement); ok {
		r0 = rf(ctx, settlement)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Settlement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Settlement) error); ok {
		r1 = rf(ctx, settlement)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettlementService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSettlementService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - settlement *domain.Settlement
func (_e *MockSettlementService_Expecter) Create(ctx interface{}, settlement interface{}) *MockSettlementService_Create_Call {
	return &MockSettlementService_Create_Call{Call: _e.mock.On("Create", ctx, settlement)}
}

func (_c *MockSettlementService_Create_Call) Run(run func(ctx context.Context, settlement *domain.Settlement)) *MockSettlementService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Settlement))
	})
	return _c
}

func (_c *MockSettlementService_Create_Call) Return(_a0 *domain.Settlement, _a1 error) *MockSettlementService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettlementService_Create_Call) RunAndReturn(run func(context.Context, *domain.Settlement) (*domain.Settlement, error)) *MockSettlementService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockSettlementService) Delete(ctx context.Context, ids []int) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettlementService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSettlementService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockSettlementService_Expecter) Delete(ctx interface{}, ids interface{}) *MockSettlementService_Delete_Call {
	return &MockSettlementService_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockSettlementService_Delete_Call) Run(run func(ctx context.Context, ids []int)) *MockSettlementService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int))
	})
	return _c
}

func (_c *MockSettlementService_Delete_Call) Return(_a0 error) *MockSettlementService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettlementService_Delete_Call) RunAndReturn(run func(context.Context, []int) error) *MockSettlementService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, filter
func (_m *MockSettlementService) Search(ctx context.Context, filter domain.SettlementFilter) ([]*domain.Settlement, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.Settlement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SettlementFilter) ([]*domain.Settlement, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SettlementFilter) []*domain.Settlement); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Settlement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SettlementFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettlementService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSettlementService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.SettlementFilter
func (_e *MockSettlementService_Expecter) Search(ctx interface{}, filter interface{}) *MockSettlementService_Search_Call {
	return &MockSettlementService_Search_Call{Call: _e.mock.On("Search", ctx, filter)}
}

func (_c *MockSettlementService_Search_Call) Run(run func(ctx context.Context, filter domain.SettlementFilter)) *MockSettlementService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SettlementFilter))
	})
	return _c
}

func (_c *MockSettlementService_Search_Call) Return(_a0 []*domain.Settlement, _a1 error) *MockSettlementService_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettlementService_Search_Call) RunAndReturn(run func(context.Context, domain.SettlementFilter) ([]*domain.Settlement, error)) *MockSettlementService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchOne provides a mock function with given fields: ctx, filter
func (_m *MockSettlementService) SearchOne(ctx context.Context, filter domain.SettlementFilter) (*domain.Settlement, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for SearchOne")
	}

	var r0 *domain.Settlement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SettlementFilter) (*domain.Settlement, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SettlementFilter) *domain.Settlement); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Settlement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SettlementFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettlementService_SearchOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchOne'
type MockSettlementService_SearchOne_Call struct {
	*mock.Call
}

// SearchOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.SettlementFilter
func (_e *MockSettlementService_Expecter) SearchOne(ctx interface{}, filter interface{}) *MockSettlementService_SearchOne_Call {
	return &MockSettlementService_SearchOne_Call{Call: _e.mock.On("SearchOne", ctx, filter)}
}

func (_c *MockSettlementService_SearchOne_Call) Run(run func(ctx context.Context, filter domain.SettlementFilter)) *MockSettlementService_SearchOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SettlementFilter))
	})
	return _c
}

func (_c *MockSettlementService_SearchOne_Call) Return(_a0 *domain.Settlement, _a1 error) *MockSettlementService_SearchOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettlementService_SearchOne_Call) RunAndReturn(run func(context.Context, domain.SettlementFilter) (*domain.Settlement, error)) *MockSettlementService_SearchOne_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, settlement
func (_m *MockSettlementService) Update(ctx context.Context, settlement *domain.Settlement) error {
	ret := _m.Called(ctx, settlement)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Settlement) error); ok {
		r0 = rf(ctx, settlement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettlementService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSettlementService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - settlement *domain.Settlement
func (_e *MockSettlementService_Expecter) Update(ctx interface{}, settlement interface{}) *MockSettlementService_Update_Call {
	return &MockSettlementService_Update_Call{Call: _e.mock.On("Update", ctx, settlement)}
}

func (_c *MockSettlementService_Update_Call) Run(run func(ctx context.Context, settlement *domain.Settlement)) *MockSettlementService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Settlement))
	})
	return _c
}

func (_c *MockSettlementService_Update_Call) Return(_a0 error) *MockSettlementService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettlementService_Update_Call) RunAndReturn(run func(context.Context, *domain.Settlement) error) *MockSettlementService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSettlementService creates a new instance of MockSettlementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettlementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettlementService {
	mock := &MockSettlementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
