// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockChargeRepository is an autogenerated mock type for the ChargeRepository type
type MockChargeRepository struct {
	mock.Mock
}

type MockChargeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChargeRepository) EXPECT() *MockChargeRepository_Expecter {
	return &MockChargeRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx, options
func (_m *MockChargeRepository) Count(ctx context.Context, options domain.ChargeSearchOptions) (int64, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChargeSearchOptions) (int64, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChargeSearchOptions) int64); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ChargeSearchOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChargeRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockChargeRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - options domain.ChargeSearchOptions
func (_e *MockChargeRepository_Expecter) Count(ctx interface{}, options interface{}) *MockChargeRepository_Count_Call {
	return &MockChargeRepository_Count_Call{Call: _e.mock.On("Count", ctx, options)}
}

func (_c *MockChargeRepository_Count_Call) Run(run func(ctx context.Context, options domain.ChargeSearchOptions)) *MockChargeRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ChargeSearchOptions))
	})
	return _c
}

func (_c *MockChargeRepository_Count_Call) Return(_a0 int64, _a1 error) *MockChargeRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChargeRepository_Count_Call) RunAndReturn(run func(context.Context, domain.ChargeSearchOptions) (int64, error)) *MockChargeRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, charge
func (_m *MockChargeRepository) Create(ctx context.Context, charge *domain.Charge) (*domain.Charge, error) {
	ret := _m.Called(ctx, charge)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Charge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Charge) (*domain.Charge, error)); ok {
		return rf(ctx, charge)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Charge) *domain.Charge); ok {
		r0 = rf(ctx, charge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Charge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Charge) error); ok {
		r1 = rf(ctx, charge)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChargeRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChargeRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - charge *domain.Charge
func (_e *MockChargeRepository_Expecter) Create(ctx interface{}, charge interface{}) *MockChargeRepository_Create_Call {
	return &MockChargeRepository_Create_Call{Call: _e.mock.On("Create", ctx, charge)}
}

func (_c *MockChargeRepository_Create_Call) Run(run func(ctx context.Context, charge *domain.Charge)) *MockChargeRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Charge))
	})
	return _c
}

func (_c *MockChargeRepository_Create_Call) Return(_a0 *domain.Charge, _a1 error) *MockChargeRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChargeRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Charge) (*domain.Charge, error)) *MockChargeRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockChargeRepository) GetByID(ctx context.Context, id int) (*domain.Charge, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Charge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Charge, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Charge); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Charge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChargeRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChargeRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockChargeRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockChargeRepository_GetByID_Call {
	return &MockChargeRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockChargeRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockChargeRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockChargeRepository_GetByID_Call) Return(_a0 *domain.Charge, _a1 error) *MockChargeRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChargeRepository_GetByID_Call) RunAndReturn(run func(context.Context, int) (*domain.Charge, error)) *MockChargeRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, options
func (_m *MockChargeRepository) Search(ctx context.Context, options domain.ChargeSearchOptions) ([]*domain.Charge, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.Charge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChargeSearchOptions) ([]*domain.Charge, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ChargeSearchOptions) []*domain.Charge); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Charge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ChargeSearchOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChargeRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockChargeRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - options domain.ChargeSearchOptions
func (_e *MockChargeRepository_Expecter) Search(ctx interface{}, options interface{}) *MockChargeRepository_Search_Call {
	return &MockChargeRepository_Search_Call{Call: _e.mock.On("Search", ctx, options)}
}

func (_c *MockChargeRepository_Search_Call) Run(run func(ctx context.Context, options domain.ChargeSearchOptions)) *MockChargeRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ChargeSearchOptions))
	})
	return _c
}

func (_c *MockChargeRepository_Search_Call) Return(_a0 []*domain.Charge, _a1 error) *MockChargeRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChargeRepository_Search_Call) RunAndReturn(run func(context.Context, domain.ChargeSearchOptions) ([]*domain.Charge, error)) *MockChargeRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, charge
func (_m *MockChargeRepository) Update(ctx context.Context, charge *domain.Charge) error {
	ret := _m.Called(ctx, charge)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Charge) error); ok {
		r0 = rf(ctx, charge)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChargeRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChargeRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - charge *domain.Charge
func (_e *MockChargeRepository_Expecter) Update(ctx interface{}, charge interface{}) *MockChargeRepository_Update_Call {
	return &MockChargeRepository_Update_Call{Call: _e.mock.On("Update", ctx, charge)}
}

func (_c *MockChargeRepository_Update_Call) Run(run func(ctx context.Context, charge *domain.Charge)) *MockChargeRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Charge))
	})
	return _c
}

func (_c *MockChargeRepository_Update_Call) Return(_a0 error) *MockChargeRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChargeRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Charge) error) *MockChargeRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChargeRepository creates a new instance of MockChargeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChargeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChargeRepository {
	mock := &MockChargeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
