// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *MockAuthService) Login(ctx context.Context, email string, password string) (*domain.User, string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 *domain.User, _a1 string, _a2 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, string, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// OAuthCallback provides a mock function with given fields: ctx, provider, user, providerID
func (_m *MockAuthService) OAuthCallback(ctx context.Context, provider string, user *domain.User, providerID string) (*domain.User, string, error) {
	ret := _m.Called(ctx, provider, user, providerID)

	if len(ret) == 0 {
		panic("no return value specified for OAuthCallback")
	}

	var r0 *domain.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.User, string) (*domain.User, string, error)); ok {
		return rf(ctx, provider, user, providerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.User, string) *domain.User); ok {
		r0 = rf(ctx, provider, user, providerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.User, string) string); ok {
		r1 = rf(ctx, provider, user, providerID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *domain.User, string) error); ok {
		r2 = rf(ctx, provider, user, providerID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthService_OAuthCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OAuthCallback'
type MockAuthService_OAuthCallback_Call struct {
	*mock.Call
}

// OAuthCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - user *domain.User
//   - providerID string
func (_e *MockAuthService_Expecter) OAuthCallback(ctx interface{}, provider interface{}, user interface{}, providerID interface{}) *MockAuthService_OAuthCallback_Call {
	return &MockAuthService_OAuthCallback_Call{Call: _e.mock.On("OAuthCallback", ctx, provider, user, providerID)}
}

func (_c *MockAuthService_OAuthCallback_Call) Run(run func(ctx context.Context, provider string, user *domain.User, providerID string)) *MockAuthService_OAuthCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*domain.User), args[3].(string))
	})
	return _c
}

func (_c *MockAuthService_OAuthCallback_Call) Return(_a0 *domain.User, _a1 string, _a2 error) *MockAuthService_OAuthCallback_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthService_OAuthCallback_Call) RunAndReturn(run func(context.Context, string, *domain.User, string) (*domain.User, string, error)) *MockAuthService_OAuthCallback_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, name, email, password
func (_m *MockAuthService) Register(ctx context.Context, name string, email string, password string) (*domain.User, string, error) {
	ret := _m.Called(ctx, name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.User, string, error)); ok {
		return rf(ctx, name, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.User); ok {
		r0 = rf(ctx, name, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) string); ok {
		r1 = rf(ctx, name, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, name, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - password string
func (_e *MockAuthService_Expecter) Register(ctx interface{}, name interface{}, email interface{}, password interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, name, email, password)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, name string, email string, password string)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(_a0 *domain.User, _a1 string, _a2 error) *MockAuthService_Register_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(context.Context, string, string, string) (*domain.User, string, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPasswordReset provides a mock function with given fields: ctx, email
func (_m *MockAuthService) RequestPasswordReset(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_RequestPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPasswordReset'
type MockAuthService_RequestPasswordReset_Call struct {
	*mock.Call
}

// RequestPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthService_Expecter) RequestPasswordReset(ctx interface{}, email interface{}) *MockAuthService_RequestPasswordReset_Call {
	return &MockAuthService_RequestPasswordReset_Call{Call: _e.mock.On("RequestPasswordReset", ctx, email)}
}

func (_c *MockAuthService_RequestPasswordReset_Call) Run(run func(ctx context.Context, email string)) *MockAuthService_RequestPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_RequestPasswordReset_Call) Return(_a0 error) *MockAuthService_RequestPasswordReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_RequestPasswordReset_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthService_RequestPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, email, token, newPassword
func (_m *MockAuthService) ResetPassword(ctx context.Context, email string, token string, newPassword string) error {
	ret := _m.Called(ctx, email, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, email, token, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAuthService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - token string
//   - newPassword string
func (_e *MockAuthService_Expecter) ResetPassword(ctx interface{}, email interface{}, token interface{}, newPassword interface{}) *MockAuthService_ResetPassword_Call {
	return &MockAuthService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, email, token, newPassword)}
}

func (_c *MockAuthService_ResetPassword_Call) Run(run func(ctx context.Context, email string, token string, newPassword string)) *MockAuthService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthService_ResetPassword_Call) Return(_a0 error) *MockAuthService_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_ResetPassword_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockAuthService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: ctx, token
func (_m *MockAuthService) ValidateToken(ctx context.Context, token string) (*domain.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockAuthService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthService_Expecter) ValidateToken(ctx interface{}, token interface{}) *MockAuthService_ValidateToken_Call {
	return &MockAuthService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, token)}
}

func (_c *MockAuthService_ValidateToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_ValidateToken_Call) Return(_a0 *domain.User, _a1 error) *MockAuthService_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_ValidateToken_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockAuthService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
