// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUserConnectionRepository is an autogenerated mock type for the UserConnectionRepository type
type MockUserConnectionRepository struct {
	mock.Mock
}

type MockUserConnectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserConnectionRepository) EXPECT() *MockUserConnectionRepository_Expecter {
	return &MockUserConnectionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userConnection
func (_m *MockUserConnectionRepository) Create(ctx context.Context, userConnection *domain.UserConnection) (*domain.UserConnection, error) {
	ret := _m.Called(ctx, userConnection)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.UserConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserConnection) (*domain.UserConnection, error)); ok {
		return rf(ctx, userConnection)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserConnection) *domain.UserConnection); ok {
		r0 = rf(ctx, userConnection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.UserConnection) error); ok {
		r1 = rf(ctx, userConnection)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserConnectionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserConnectionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userConnection *domain.UserConnection
func (_e *MockUserConnectionRepository_Expecter) Create(ctx interface{}, userConnection interface{}) *MockUserConnectionRepository_Create_Call {
	return &MockUserConnectionRepository_Create_Call{Call: _e.mock.On("Create", ctx, userConnection)}
}

func (_c *MockUserConnectionRepository_Create_Call) Run(run func(ctx context.Context, userConnection *domain.UserConnection)) *MockUserConnectionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.UserConnection))
	})
	return _c
}

func (_c *MockUserConnectionRepository_Create_Call) Return(_a0 *domain.UserConnection, _a1 error) *MockUserConnectionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserConnectionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.UserConnection) (*domain.UserConnection, error)) *MockUserConnectionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserConnectionRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserConnectionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserConnectionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockUserConnectionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockUserConnectionRepository_Delete_Call {
	return &MockUserConnectionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserConnectionRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockUserConnectionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserConnectionRepository_Delete_Call) Return(_a0 error) *MockUserConnectionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserConnectionRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockUserConnectionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, options
func (_m *MockUserConnectionRepository) Search(ctx context.Context, options domain.UserConnectionSearchOptions) ([]*domain.UserConnection, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.UserConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserConnectionSearchOptions) ([]*domain.UserConnection, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserConnectionSearchOptions) []*domain.UserConnection); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserConnectionSearchOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserConnectionRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockUserConnectionRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - options domain.UserConnectionSearchOptions
func (_e *MockUserConnectionRepository_Expecter) Search(ctx interface{}, options interface{}) *MockUserConnectionRepository_Search_Call {
	return &MockUserConnectionRepository_Search_Call{Call: _e.mock.On("Search", ctx, options)}
}

func (_c *MockUserConnectionRepository_Search_Call) Run(run func(ctx context.Context, options domain.UserConnectionSearchOptions)) *MockUserConnectionRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserConnectionSearchOptions))
	})
	return _c
}

func (_c *MockUserConnectionRepository_Search_Call) Return(_a0 []*domain.UserConnection, _a1 error) *MockUserConnectionRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserConnectionRepository_Search_Call) RunAndReturn(run func(context.Context, domain.UserConnectionSearchOptions) ([]*domain.UserConnection, error)) *MockUserConnectionRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userConnection
func (_m *MockUserConnectionRepository) Update(ctx context.Context, userConnection *domain.UserConnection) error {
	ret := _m.Called(ctx, userConnection)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserConnection) error); ok {
		r0 = rf(ctx, userConnection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserConnectionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserConnectionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userConnection *domain.UserConnection
func (_e *MockUserConnectionRepository_Expecter) Update(ctx interface{}, userConnection interface{}) *MockUserConnectionRepository_Update_Call {
	return &MockUserConnectionRepository_Update_Call{Call: _e.mock.On("Update", ctx, userConnection)}
}

func (_c *MockUserConnectionRepository_Update_Call) Run(run func(ctx context.Context, userConnection *domain.UserConnection)) *MockUserConnectionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.UserConnection))
	})
	return _c
}

func (_c *MockUserConnectionRepository_Update_Call) Return(_a0 error) *MockUserConnectionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserConnectionRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.UserConnection) error) *MockUserConnectionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserConnectionRepository creates a new instance of MockUserConnectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserConnectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserConnectionRepository {
	mock := &MockUserConnectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
