// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, transaction
func (_m *MockTransactionRepository) Create(ctx context.Context, transaction *domain.Transaction) (*domain.Transaction, error) {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) (*domain.Transaction, error)); ok {
		return rf(ctx, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) *domain.Transaction); ok {
		r0 = rf(ctx, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Transaction) error); ok {
		r1 = rf(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *domain.Transaction
func (_e *MockTransactionRepository_Expecter) Create(ctx interface{}, transaction interface{}) *MockTransactionRepository_Create_Call {
	return &MockTransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, transaction)}
}

func (_c *MockTransactionRepository_Create_Call) Run(run func(ctx context.Context, transaction *domain.Transaction)) *MockTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_Create_Call) Return(_a0 *domain.Transaction, _a1 error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Transaction) (*domain.Transaction, error)) *MockTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ids
func (_m *MockTransactionRepository) Delete(ctx context.Context, ids []int) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockTransactionRepository_Expecter) Delete(ctx interface{}, ids interface{}) *MockTransactionRepository_Delete_Call {
	return &MockTransactionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ids)}
}

func (_c *MockTransactionRepository_Delete_Call) Run(run func(ctx context.Context, ids []int)) *MockTransactionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int))
	})
	return _c
}

func (_c *MockTransactionRepository_Delete_Call) Return(_a0 error) *MockTransactionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_Delete_Call) RunAndReturn(run func(context.Context, []int) error) *MockTransactionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupedByRecurrences provides a mock function with given fields: ctx, userID, recurrenceIDs
func (_m *MockTransactionRepository) GetGroupedByRecurrences(ctx context.Context, userID *int, recurrenceIDs []int) (map[int][]*domain.Transaction, error) {
	ret := _m.Called(ctx, userID, recurrenceIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupedByRecurrences")
	}

	var r0 map[int][]*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int, []int) (map[int][]*domain.Transaction, error)); ok {
		return rf(ctx, userID, recurrenceIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int, []int) map[int][]*domain.Transaction); ok {
		r0 = rf(ctx, userID, recurrenceIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int][]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *int, []int) error); ok {
		r1 = rf(ctx, userID, recurrenceIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_GetGroupedByRecurrences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupedByRecurrences'
type MockTransactionRepository_GetGroupedByRecurrences_Call struct {
	*mock.Call
}

// GetGroupedByRecurrences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *int
//   - recurrenceIDs []int
func (_e *MockTransactionRepository_Expecter) GetGroupedByRecurrences(ctx interface{}, userID interface{}, recurrenceIDs interface{}) *MockTransactionRepository_GetGroupedByRecurrences_Call {
	return &MockTransactionRepository_GetGroupedByRecurrences_Call{Call: _e.mock.On("GetGroupedByRecurrences", ctx, userID, recurrenceIDs)}
}

func (_c *MockTransactionRepository_GetGroupedByRecurrences_Call) Run(run func(ctx context.Context, userID *int, recurrenceIDs []int)) *MockTransactionRepository_GetGroupedByRecurrences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*int), args[2].([]int))
	})
	return _c
}

func (_c *MockTransactionRepository_GetGroupedByRecurrences_Call) Return(_a0 map[int][]*domain.Transaction, _a1 error) *MockTransactionRepository_GetGroupedByRecurrences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_GetGroupedByRecurrences_Call) RunAndReturn(run func(context.Context, *int, []int) (map[int][]*domain.Transaction, error)) *MockTransactionRepository_GetGroupedByRecurrences_Call {
	_c.Call.Return(run)
	return _c
}

// GetSourceTransactionIDs provides a mock function with given fields: ctx, linkedTransactionID
func (_m *MockTransactionRepository) GetSourceTransactionIDs(ctx context.Context, linkedTransactionID int) ([]int, error) {
	ret := _m.Called(ctx, linkedTransactionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSourceTransactionIDs")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return rf(ctx, linkedTransactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = rf(ctx, linkedTransactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, linkedTransactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_GetSourceTransactionIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSourceTransactionIDs'
type MockTransactionRepository_GetSourceTransactionIDs_Call struct {
	*mock.Call
}

// GetSourceTransactionIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - linkedTransactionID int
func (_e *MockTransactionRepository_Expecter) GetSourceTransactionIDs(ctx interface{}, linkedTransactionID interface{}) *MockTransactionRepository_GetSourceTransactionIDs_Call {
	return &MockTransactionRepository_GetSourceTransactionIDs_Call{Call: _e.mock.On("GetSourceTransactionIDs", ctx, linkedTransactionID)}
}

func (_c *MockTransactionRepository_GetSourceTransactionIDs_Call) Run(run func(ctx context.Context, linkedTransactionID int)) *MockTransactionRepository_GetSourceTransactionIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionRepository_GetSourceTransactionIDs_Call) Return(_a0 []int, _a1 error) *MockTransactionRepository_GetSourceTransactionIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_GetSourceTransactionIDs_Call) RunAndReturn(run func(context.Context, int) ([]int, error)) *MockTransactionRepository_GetSourceTransactionIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, filter
func (_m *MockTransactionRepository) Search(ctx context.Context, filter domain.TransactionFilter) ([]*domain.Transaction, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransactionFilter) ([]*domain.Transaction, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransactionFilter) []*domain.Transaction); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TransactionFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockTransactionRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.TransactionFilter
func (_e *MockTransactionRepository_Expecter) Search(ctx interface{}, filter interface{}) *MockTransactionRepository_Search_Call {
	return &MockTransactionRepository_Search_Call{Call: _e.mock.On("Search", ctx, filter)}
}

func (_c *MockTransactionRepository_Search_Call) Run(run func(ctx context.Context, filter domain.TransactionFilter)) *MockTransactionRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TransactionFilter))
	})
	return _c
}

func (_c *MockTransactionRepository_Search_Call) Return(_a0 []*domain.Transaction, _a1 error) *MockTransactionRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_Search_Call) RunAndReturn(run func(context.Context, domain.TransactionFilter) ([]*domain.Transaction, error)) *MockTransactionRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchOne provides a mock function with given fields: ctx, filter
func (_m *MockTransactionRepository) SearchOne(ctx context.Context, filter domain.TransactionFilter) (*domain.Transaction, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for SearchOne")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransactionFilter) (*domain.Transaction, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransactionFilter) *domain.Transaction); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TransactionFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_SearchOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchOne'
type MockTransactionRepository_SearchOne_Call struct {
	*mock.Call
}

// SearchOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.TransactionFilter
func (_e *MockTransactionRepository_Expecter) SearchOne(ctx interface{}, filter interface{}) *MockTransactionRepository_SearchOne_Call {
	return &MockTransactionRepository_SearchOne_Call{Call: _e.mock.On("SearchOne", ctx, filter)}
}

func (_c *MockTransactionRepository_SearchOne_Call) Run(run func(ctx context.Context, filter domain.TransactionFilter)) *MockTransactionRepository_SearchOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TransactionFilter))
	})
	return _c
}

func (_c *MockTransactionRepository_SearchOne_Call) Return(_a0 *domain.Transaction, _a1 error) *MockTransactionRepository_SearchOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_SearchOne_Call) RunAndReturn(run func(context.Context, domain.TransactionFilter) (*domain.Transaction, error)) *MockTransactionRepository_SearchOne_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, transaction
func (_m *MockTransactionRepository) Update(ctx context.Context, transaction *domain.Transaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *domain.Transaction
func (_e *MockTransactionRepository_Expecter) Update(ctx interface{}, transaction interface{}) *MockTransactionRepository_Update_Call {
	return &MockTransactionRepository_Update_Call{Call: _e.mock.On("Update", ctx, transaction)}
}

func (_c *MockTransactionRepository_Update_Call) Run(run func(ctx context.Context, transaction *domain.Transaction)) *MockTransactionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_Update_Call) Return(_a0 error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Transaction) error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
