// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockPushSubscriptionRepository is an autogenerated mock type for the PushSubscriptionRepository type
type MockPushSubscriptionRepository struct {
	mock.Mock
}

type MockPushSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPushSubscriptionRepository) EXPECT() *MockPushSubscriptionRepository_Expecter {
	return &MockPushSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// DeleteByEndpoint provides a mock function with given fields: ctx, userID, endpoint
func (_m *MockPushSubscriptionRepository) DeleteByEndpoint(ctx context.Context, userID int, endpoint string) error {
	ret := _m.Called(ctx, userID, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByEndpoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, userID, endpoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPushSubscriptionRepository_DeleteByEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByEndpoint'
type MockPushSubscriptionRepository_DeleteByEndpoint_Call struct {
	*mock.Call
}

// DeleteByEndpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - endpoint string
func (_e *MockPushSubscriptionRepository_Expecter) DeleteByEndpoint(ctx interface{}, userID interface{}, endpoint interface{}) *MockPushSubscriptionRepository_DeleteByEndpoint_Call {
	return &MockPushSubscriptionRepository_DeleteByEndpoint_Call{Call: _e.mock.On("DeleteByEndpoint", ctx, userID, endpoint)}
}

func (_c *MockPushSubscriptionRepository_DeleteByEndpoint_Call) Run(run func(ctx context.Context, userID int, endpoint string)) *MockPushSubscriptionRepository_DeleteByEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockPushSubscriptionRepository_DeleteByEndpoint_Call) Return(_a0 error) *MockPushSubscriptionRepository_DeleteByEndpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPushSubscriptionRepository_DeleteByEndpoint_Call) RunAndReturn(run func(context.Context, int, string) error) *MockPushSubscriptionRepository_DeleteByEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByEndpointAdmin provides a mock function with given fields: ctx, endpoint
func (_m *MockPushSubscriptionRepository) DeleteByEndpointAdmin(ctx context.Context, endpoint string) error {
	ret := _m.Called(ctx, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByEndpointAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, endpoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPushSubscriptionRepository_DeleteByEndpointAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByEndpointAdmin'
type MockPushSubscriptionRepository_DeleteByEndpointAdmin_Call struct {
	*mock.Call
}

// DeleteByEndpointAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - endpoint string
func (_e *MockPushSubscriptionRepository_Expecter) DeleteByEndpointAdmin(ctx interface{}, endpoint interface{}) *MockPushSubscriptionRepository_DeleteByEndpointAdmin_Call {
	return &MockPushSubscriptionRepository_DeleteByEndpointAdmin_Call{Call: _e.mock.On("DeleteByEndpointAdmin", ctx, endpoint)}
}

func (_c *MockPushSubscriptionRepository_DeleteByEndpointAdmin_Call) Run(run func(ctx context.Context, endpoint string)) *MockPushSubscriptionRepository_DeleteByEndpointAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPushSubscriptionRepository_DeleteByEndpointAdmin_Call) Return(_a0 error) *MockPushSubscriptionRepository_DeleteByEndpointAdmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPushSubscriptionRepository_DeleteByEndpointAdmin_Call) RunAndReturn(run func(context.Context, string) error) *MockPushSubscriptionRepository_DeleteByEndpointAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsForUser provides a mock function with given fields: ctx, userID, endpoint
func (_m *MockPushSubscriptionRepository) ExistsForUser(ctx context.Context, userID int, endpoint string) (bool, error) {
	ret := _m.Called(ctx, userID, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for ExistsForUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (bool, error)); ok {
		return rf(ctx, userID, endpoint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) bool); ok {
		r0 = rf(ctx, userID, endpoint)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, userID, endpoint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPushSubscriptionRepository_ExistsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsForUser'
type MockPushSubscriptionRepository_ExistsForUser_Call struct {
	*mock.Call
}

// ExistsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - endpoint string
func (_e *MockPushSubscriptionRepository_Expecter) ExistsForUser(ctx interface{}, userID interface{}, endpoint interface{}) *MockPushSubscriptionRepository_ExistsForUser_Call {
	return &MockPushSubscriptionRepository_ExistsForUser_Call{Call: _e.mock.On("ExistsForUser", ctx, userID, endpoint)}
}

func (_c *MockPushSubscriptionRepository_ExistsForUser_Call) Run(run func(ctx context.Context, userID int, endpoint string)) *MockPushSubscriptionRepository_ExistsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockPushSubscriptionRepository_ExistsForUser_Call) Return(_a0 bool, _a1 error) *MockPushSubscriptionRepository_ExistsForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPushSubscriptionRepository_ExistsForUser_Call) RunAndReturn(run func(context.Context, int, string) (bool, error)) *MockPushSubscriptionRepository_ExistsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, sub
func (_m *MockPushSubscriptionRepository) Upsert(ctx context.Context, sub *domain.PushSubscription) error {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PushSubscription) error); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPushSubscriptionRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockPushSubscriptionRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - sub *domain.PushSubscription
func (_e *MockPushSubscriptionRepository_Expecter) Upsert(ctx interface{}, sub interface{}) *MockPushSubscriptionRepository_Upsert_Call {
	return &MockPushSubscriptionRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, sub)}
}

func (_c *MockPushSubscriptionRepository_Upsert_Call) Run(run func(ctx context.Context, sub *domain.PushSubscription)) *MockPushSubscriptionRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.PushSubscription))
	})
	return _c
}

func (_c *MockPushSubscriptionRepository_Upsert_Call) Return(_a0 error) *MockPushSubscriptionRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPushSubscriptionRepository_Upsert_Call) RunAndReturn(run func(context.Context, *domain.PushSubscription) error) *MockPushSubscriptionRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPushSubscriptionRepository creates a new instance of MockPushSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPushSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPushSubscriptionRepository {
	mock := &MockPushSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
