// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, category
func (_m *MockCategoryRepository) Create(ctx context.Context, category *domain.Category) (*domain.Category, error) {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Category) (*domain.Category, error)); ok {
		return rf(ctx, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Category) *domain.Category); ok {
		r0 = rf(ctx, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Category) error); ok {
		r1 = rf(ctx, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category *domain.Category
func (_e *MockCategoryRepository_Expecter) Create(ctx interface{}, category interface{}) *MockCategoryRepository_Create_Call {
	return &MockCategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, category)}
}

func (_c *MockCategoryRepository_Create_Call) Run(run func(ctx context.Context, category *domain.Category)) *MockCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Category))
	})
	return _c
}

func (_c *MockCategoryRepository_Create_Call) Return(_a0 *domain.Category, _a1 error) *MockCategoryRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Category) (*domain.Category, error)) *MockCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCategoryRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCategoryRepository_Delete_Call {
	return &MockCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCategoryRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) Return(_a0 error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) GetByID(ctx context.Context, id int) (*domain.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCategoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCategoryRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockCategoryRepository_GetByID_Call {
	return &MockCategoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCategoryRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockCategoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCategoryRepository_GetByID_Call) Return(_a0 *domain.Category, _a1 error) *MockCategoryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_GetByID_Call) RunAndReturn(run func(context.Context, int) (*domain.Category, error)) *MockCategoryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockCategoryRepository) GetByUserID(ctx context.Context, userID int) ([]*domain.Category, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Category, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Category); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockCategoryRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockCategoryRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockCategoryRepository_GetByUserID_Call {
	return &MockCategoryRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockCategoryRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockCategoryRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCategoryRepository_GetByUserID_Call) Return(_a0 []*domain.Category, _a1 error) *MockCategoryRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, int) ([]*domain.Category, error)) *MockCategoryRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserIDWithChildren provides a mock function with given fields: ctx, userID
func (_m *MockCategoryRepository) GetByUserIDWithChildren(ctx context.Context, userID int) ([]*domain.Category, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIDWithChildren")
	}

	var r0 []*domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Category, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Category); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_GetByUserIDWithChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserIDWithChildren'
type MockCategoryRepository_GetByUserIDWithChildren_Call struct {
	*mock.Call
}

// GetByUserIDWithChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockCategoryRepository_Expecter) GetByUserIDWithChildren(ctx interface{}, userID interface{}) *MockCategoryRepository_GetByUserIDWithChildren_Call {
	return &MockCategoryRepository_GetByUserIDWithChildren_Call{Call: _e.mock.On("GetByUserIDWithChildren", ctx, userID)}
}

func (_c *MockCategoryRepository_GetByUserIDWithChildren_Call) Run(run func(ctx context.Context, userID int)) *MockCategoryRepository_GetByUserIDWithChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCategoryRepository_GetByUserIDWithChildren_Call) Return(_a0 []*domain.Category, _a1 error) *MockCategoryRepository_GetByUserIDWithChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_GetByUserIDWithChildren_Call) RunAndReturn(run func(context.Context, int) ([]*domain.Category, error)) *MockCategoryRepository_GetByUserIDWithChildren_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, category
func (_m *MockCategoryRepository) Update(ctx context.Context, category *domain.Category) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Category) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - category *domain.Category
func (_e *MockCategoryRepository_Expecter) Update(ctx interface{}, category interface{}) *MockCategoryRepository_Update_Call {
	return &MockCategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *MockCategoryRepository_Update_Call) Run(run func(ctx context.Context, category *domain.Category)) *MockCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Category))
	})
	return _c
}

func (_c *MockCategoryRepository_Update_Call) Return(_a0 error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Category) error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
