// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function with given fields: ctx, userID, id
func (_m *MockAccountService) Activate(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountService_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type MockAccountService_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockAccountService_Expecter) Activate(ctx interface{}, userID interface{}, id interface{}) *MockAccountService_Activate_Call {
	return &MockAccountService_Activate_Call{Call: _e.mock.On("Activate", ctx, userID, id)}
}

func (_c *MockAccountService_Activate_Call) Run(run func(ctx context.Context, userID int, id int)) *MockAccountService_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAccountService_Activate_Call) Return(_a0 error) *MockAccountService_Activate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountService_Activate_Call) RunAndReturn(run func(context.Context, int, int) error) *MockAccountService_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userID, account
func (_m *MockAccountService) Create(ctx context.Context, userID int, account *domain.Account) (*domain.Account, error) {
	ret := _m.Called(ctx, userID, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Account) (*domain.Account, error)); ok {
		return rf(ctx, userID, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Account) *domain.Account); ok {
		r0 = rf(ctx, userID, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *domain.Account) error); ok {
		r1 = rf(ctx, userID, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - account *domain.Account
func (_e *MockAccountService_Expecter) Create(ctx interface{}, userID interface{}, account interface{}) *MockAccountService_Create_Call {
	return &MockAccountService_Create_Call{Call: _e.mock.On("Create", ctx, userID, account)}
}

func (_c *MockAccountService_Create_Call) Run(run func(ctx context.Context, userID int, account *domain.Account)) *MockAccountService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Account))
	})
	return _c
}

func (_c *MockAccountService_Create_Call) Return(_a0 *domain.Account, _a1 error) *MockAccountService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_Create_Call) RunAndReturn(run func(context.Context, int, *domain.Account) (*domain.Account, error)) *MockAccountService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function with given fields: ctx, userID, id
func (_m *MockAccountService) Deactivate(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountService_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockAccountService_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockAccountService_Expecter) Deactivate(ctx interface{}, userID interface{}, id interface{}) *MockAccountService_Deactivate_Call {
	return &MockAccountService_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, userID, id)}
}

func (_c *MockAccountService_Deactivate_Call) Run(run func(ctx context.Context, userID int, id int)) *MockAccountService_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAccountService_Deactivate_Call) Return(_a0 error) *MockAccountService_Deactivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountService_Deactivate_Call) RunAndReturn(run func(context.Context, int, int) error) *MockAccountService_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id, strategy, targetAccountID
func (_m *MockAccountService) Delete(ctx context.Context, userID int, id int, strategy domain.AccountDeletionStrategy, targetAccountID *int) error {
	ret := _m.Called(ctx, userID, id, strategy, targetAccountID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, domain.AccountDeletionStrategy, *int) error); ok {
		r0 = rf(ctx, userID, id, strategy, targetAccountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
//   - strategy domain.AccountDeletionStrategy
//   - targetAccountID *int
func (_e *MockAccountService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}, strategy interface{}, targetAccountID interface{}) *MockAccountService_Delete_Call {
	return &MockAccountService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id, strategy, targetAccountID)}
}

func (_c *MockAccountService_Delete_Call) Run(run func(ctx context.Context, userID int, id int, strategy domain.AccountDeletionStrategy, targetAccountID *int)) *MockAccountService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(domain.AccountDeletionStrategy), args[4].(*int))
	})
	return _c
}

func (_c *MockAccountService_Delete_Call) Return(_a0 error) *MockAccountService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountService_Delete_Call) RunAndReturn(run func(context.Context, int, int, domain.AccountDeletionStrategy, *int) error) *MockAccountService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *MockAccountService) GetByID(ctx context.Context, userID int, id int) (*domain.Account, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*domain.Account, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *domain.Account); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAccountService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockAccountService_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *MockAccountService_GetByID_Call {
	return &MockAccountService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *MockAccountService_GetByID_Call) Run(run func(ctx context.Context, userID int, id int)) *MockAccountService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAccountService_GetByID_Call) Return(_a0 *domain.Account, _a1 error) *MockAccountService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_GetByID_Call) RunAndReturn(run func(context.Context, int, int) (*domain.Account, error)) *MockAccountService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeletionInfo provides a mock function with given fields: ctx, userID, id
func (_m *MockAccountService) GetDeletionInfo(ctx context.Context, userID int, id int) (*domain.AccountDeletionInfo, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDeletionInfo")
	}

	var r0 *domain.AccountDeletionInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*domain.AccountDeletionInfo, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *domain.AccountDeletionInfo); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AccountDeletionInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_GetDeletionInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeletionInfo'
type MockAccountService_GetDeletionInfo_Call struct {
	*mock.Call
}

// GetDeletionInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockAccountService_Expecter) GetDeletionInfo(ctx interface{}, userID interface{}, id interface{}) *MockAccountService_GetDeletionInfo_Call {
	return &MockAccountService_GetDeletionInfo_Call{Call: _e.mock.On("GetDeletionInfo", ctx, userID, id)}
}

func (_c *MockAccountService_GetDeletionInfo_Call) Run(run func(ctx context.Context, userID int, id int)) *MockAccountService_GetDeletionInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAccountService_GetDeletionInfo_Call) Return(_a0 *domain.AccountDeletionInfo, _a1 error) *MockAccountService_GetDeletionInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_GetDeletionInfo_Call) RunAndReturn(run func(context.Context, int, int) (*domain.AccountDeletionInfo, error)) *MockAccountService_GetDeletionInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Reorder provides a mock function with given fields: ctx, userID, orderedIDs
func (_m *MockAccountService) Reorder(ctx context.Context, userID int, orderedIDs []int) error {
	ret := _m.Called(ctx, userID, orderedIDs)

	if len(ret) == 0 {
		panic("no return value specified for Reorder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = rf(ctx, userID, orderedIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountService_Reorder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reorder'
type MockAccountService_Reorder_Call struct {
	*mock.Call
}

// Reorder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - orderedIDs []int
func (_e *MockAccountService_Expecter) Reorder(ctx interface{}, userID interface{}, orderedIDs interface{}) *MockAccountService_Reorder_Call {
	return &MockAccountService_Reorder_Call{Call: _e.mock.On("Reorder", ctx, userID, orderedIDs)}
}

func (_c *MockAccountService_Reorder_Call) Run(run func(ctx context.Context, userID int, orderedIDs []int)) *MockAccountService_Reorder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].([]int))
	})
	return _c
}

func (_c *MockAccountService_Reorder_Call) Return(_a0 error) *MockAccountService_Reorder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountService_Reorder_Call) RunAndReturn(run func(context.Context, int, []int) error) *MockAccountService_Reorder_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, options
func (_m *MockAccountService) Search(ctx context.Context, options domain.AccountSearchOptions) ([]*domain.Account, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AccountSearchOptions) ([]*domain.Account, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AccountSearchOptions) []*domain.Account); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AccountSearchOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockAccountService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - options domain.AccountSearchOptions
func (_e *MockAccountService_Expecter) Search(ctx interface{}, options interface{}) *MockAccountService_Search_Call {
	return &MockAccountService_Search_Call{Call: _e.mock.On("Search", ctx, options)}
}

func (_c *MockAccountService_Search_Call) Run(run func(ctx context.Context, options domain.AccountSearchOptions)) *MockAccountService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AccountSearchOptions))
	})
	return _c
}

func (_c *MockAccountService_Search_Call) Return(_a0 []*domain.Account, _a1 error) *MockAccountService_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_Search_Call) RunAndReturn(run func(context.Context, domain.AccountSearchOptions) ([]*domain.Account, error)) *MockAccountService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchOne provides a mock function with given fields: ctx, options
func (_m *MockAccountService) SearchOne(ctx context.Context, options domain.AccountSearchOptions) (*domain.Account, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for SearchOne")
	}

	var r0 *domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AccountSearchOptions) (*domain.Account, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AccountSearchOptions) *domain.Account); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AccountSearchOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_SearchOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchOne'
type MockAccountService_SearchOne_Call struct {
	*mock.Call
}

// SearchOne is a helper method to define mock.On call
//   - ctx context.Context
//   - options domain.AccountSearchOptions
func (_e *MockAccountService_Expecter) SearchOne(ctx interface{}, options interface{}) *MockAccountService_SearchOne_Call {
	return &MockAccountService_SearchOne_Call{Call: _e.mock.On("SearchOne", ctx, options)}
}

func (_c *MockAccountService_SearchOne_Call) Run(run func(ctx context.Context, options domain.AccountSearchOptions)) *MockAccountService_SearchOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AccountSearchOptions))
	})
	return _c
}

func (_c *MockAccountService_SearchOne_Call) Return(_a0 *domain.Account, _a1 error) *MockAccountService_SearchOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_SearchOne_Call) RunAndReturn(run func(context.Context, domain.AccountSearchOptions) (*domain.Account, error)) *MockAccountService_SearchOne_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, account
func (_m *MockAccountService) Update(ctx context.Context, userID int, account *domain.Account) error {
	ret := _m.Called(ctx, userID, account)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Account) error); ok {
		r0 = rf(ctx, userID, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - account *domain.Account
func (_e *MockAccountService_Expecter) Update(ctx interface{}, userID interface{}, account interface{}) *MockAccountService_Update_Call {
	return &MockAccountService_Update_Call{Call: _e.mock.On("Update", ctx, userID, account)}
}

func (_c *MockAccountService_Update_Call) Run(run func(ctx context.Context, userID int, account *domain.Account)) *MockAccountService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Account))
	})
	return _c
}

func (_c *MockAccountService_Update_Call) Return(_a0 error) *MockAccountService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountService_Update_Call) RunAndReturn(run func(context.Context, int, *domain.Account) error) *MockAccountService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
