// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockCategoryService is an autogenerated mock type for the CategoryService type
type MockCategoryService struct {
	mock.Mock
}

type MockCategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryService) EXPECT() *MockCategoryService_Expecter {
	return &MockCategoryService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, category
func (_m *MockCategoryService) Create(ctx context.Context, userID int, category *domain.Category) (*domain.Category, error) {
	ret := _m.Called(ctx, userID, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Category) (*domain.Category, error)); ok {
		return rf(ctx, userID, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Category) *domain.Category); ok {
		r0 = rf(ctx, userID, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *domain.Category) error); ok {
		r1 = rf(ctx, userID, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - category *domain.Category
func (_e *MockCategoryService_Expecter) Create(ctx interface{}, userID interface{}, category interface{}) *MockCategoryService_Create_Call {
	return &MockCategoryService_Create_Call{Call: _e.mock.On("Create", ctx, userID, category)}
}

func (_c *MockCategoryService_Create_Call) Run(run func(ctx context.Context, userID int, category *domain.Category)) *MockCategoryService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Category))
	})
	return _c
}

func (_c *MockCategoryService_Create_Call) Return(_a0 *domain.Category, _a1 error) *MockCategoryService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryService_Create_Call) RunAndReturn(run func(context.Context, int, *domain.Category) (*domain.Category, error)) *MockCategoryService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *MockCategoryService) Delete(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockCategoryService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockCategoryService_Delete_Call {
	return &MockCategoryService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockCategoryService_Delete_Call) Run(run func(ctx context.Context, userID int, id int)) *MockCategoryService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockCategoryService_Delete_Call) Return(_a0 error) *MockCategoryService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryService_Delete_Call) RunAndReturn(run func(context.Context, int, int) error) *MockCategoryService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *MockCategoryService) GetByID(ctx context.Context, userID int, id int) (domain.Category, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (domain.Category, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) domain.Category); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(domain.Category)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCategoryService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockCategoryService_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *MockCategoryService_GetByID_Call {
	return &MockCategoryService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *MockCategoryService_GetByID_Call) Run(run func(ctx context.Context, userID int, id int)) *MockCategoryService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockCategoryService_GetByID_Call) Return(_a0 domain.Category, _a1 error) *MockCategoryService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryService_GetByID_Call) RunAndReturn(run func(context.Context, int, int) (domain.Category, error)) *MockCategoryService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, options
func (_m *MockCategoryService) Search(ctx context.Context, options domain.CategorySearchOptions) ([]*domain.Category, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CategorySearchOptions) ([]*domain.Category, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CategorySearchOptions) []*domain.Category); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CategorySearchOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockCategoryService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - options domain.CategorySearchOptions
func (_e *MockCategoryService_Expecter) Search(ctx interface{}, options interface{}) *MockCategoryService_Search_Call {
	return &MockCategoryService_Search_Call{Call: _e.mock.On("Search", ctx, options)}
}

func (_c *MockCategoryService_Search_Call) Run(run func(ctx context.Context, options domain.CategorySearchOptions)) *MockCategoryService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CategorySearchOptions))
	})
	return _c
}

func (_c *MockCategoryService_Search_Call) Return(_a0 []*domain.Category, _a1 error) *MockCategoryService_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryService_Search_Call) RunAndReturn(run func(context.Context, domain.CategorySearchOptions) ([]*domain.Category, error)) *MockCategoryService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, category
func (_m *MockCategoryService) Update(ctx context.Context, userID int, category *domain.Category) error {
	ret := _m.Called(ctx, userID, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.Category) error); ok {
		r0 = rf(ctx, userID, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategoryService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - category *domain.Category
func (_e *MockCategoryService_Expecter) Update(ctx interface{}, userID interface{}, category interface{}) *MockCategoryService_Update_Call {
	return &MockCategoryService_Update_Call{Call: _e.mock.On("Update", ctx, userID, category)}
}

func (_c *MockCategoryService_Update_Call) Run(run func(ctx context.Context, userID int, category *domain.Category)) *MockCategoryService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*domain.Category))
	})
	return _c
}

func (_c *MockCategoryService_Update_Call) Return(_a0 error) *MockCategoryService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryService_Update_Call) RunAndReturn(run func(context.Context, int, *domain.Category) error) *MockCategoryService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryService creates a new instance of MockCategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryService {
	mock := &MockCategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
