// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	domain "github.com/finance_app/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockImpersonationRepository is an autogenerated mock type for the ImpersonationRepository type
type MockImpersonationRepository struct {
	mock.Mock
}

type MockImpersonationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImpersonationRepository) EXPECT() *MockImpersonationRepository_Expecter {
	return &MockImpersonationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session
func (_m *MockImpersonationRepository) Create(ctx context.Context, session *domain.ImpersonationSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ImpersonationSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockImpersonationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockImpersonationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.ImpersonationSession
func (_e *MockImpersonationRepository_Expecter) Create(ctx interface{}, session interface{}) *MockImpersonationRepository_Create_Call {
	return &MockImpersonationRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockImpersonationRepository_Create_Call) Run(run func(ctx context.Context, session *domain.ImpersonationSession)) *MockImpersonationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ImpersonationSession))
	})
	return _c
}

func (_c *MockImpersonationRepository_Create_Call) Return(_a0 error) *MockImpersonationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImpersonationRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.ImpersonationSession) error) *MockImpersonationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockImpersonationRepository) GetByID(ctx context.Context, id string) (*domain.ImpersonationSession, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.ImpersonationSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.ImpersonationSession, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ImpersonationSession); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ImpersonationSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImpersonationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockImpersonationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockImpersonationRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockImpersonationRepository_GetByID_Call {
	return &MockImpersonationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockImpersonationRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockImpersonationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockImpersonationRepository_GetByID_Call) Return(_a0 *domain.ImpersonationSession, _a1 error) *MockImpersonationRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImpersonationRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.ImpersonationSession, error)) *MockImpersonationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, id, at
func (_m *MockImpersonationRepository) Revoke(ctx context.Context, id string, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockImpersonationRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockImpersonationRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - at time.Time
func (_e *MockImpersonationRepository_Expecter) Revoke(ctx interface{}, id interface{}, at interface{}) *MockImpersonationRepository_Revoke_Call {
	return &MockImpersonationRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id, at)}
}

func (_c *MockImpersonationRepository_Revoke_Call) Run(run func(ctx context.Context, id string, at time.Time)) *MockImpersonationRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockImpersonationRepository_Revoke_Call) Return(_a0 error) *MockImpersonationRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImpersonationRepository_Revoke_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockImpersonationRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImpersonationRepository creates a new instance of MockImpersonationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImpersonationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImpersonationRepository {
	mock := &MockImpersonationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
