/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated.transactions'
import { Route as AuthenticatedChargesRouteImport } from './routes/_authenticated.charges'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated.categories'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated.accounts'
import { Route as AuthenticatedTransactionsImportRouteImport } from './routes/_authenticated.transactions_.import'
import { Route as AuthenticatedConnectWithExternalIdRouteImport } from './routes/_authenticated.connect-with.$externalId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChargesRoute = AuthenticatedChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsImportRoute =
  AuthenticatedTransactionsImportRouteImport.update({
    id: '/transactions_/import',
    path: '/transactions/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConnectWithExternalIdRoute =
  AuthenticatedConnectWithExternalIdRouteImport.update({
    id: '/connect-with/$externalId',
    path: '/connect-with/$externalId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/charges': typeof AuthenticatedChargesRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/connect-with/$externalId': typeof AuthenticatedConnectWithExternalIdRoute
  '/transactions/import': typeof AuthenticatedTransactionsImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/charges': typeof AuthenticatedChargesRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/connect-with/$externalId': typeof AuthenticatedConnectWithExternalIdRoute
  '/transactions/import': typeof AuthenticatedTransactionsImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/charges': typeof AuthenticatedChargesRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/connect-with/$externalId': typeof AuthenticatedConnectWithExternalIdRoute
  '/_authenticated/transactions_/import': typeof AuthenticatedTransactionsImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/categories'
    | '/charges'
    | '/transactions'
    | '/auth/callback'
    | '/connect-with/$externalId'
    | '/transactions/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accounts'
    | '/categories'
    | '/charges'
    | '/transactions'
    | '/auth/callback'
    | '/connect-with/$externalId'
    | '/transactions/import'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/accounts'
    | '/_authenticated/categories'
    | '/_authenticated/charges'
    | '/_authenticated/transactions'
    | '/auth/callback'
    | '/_authenticated/connect-with/$externalId'
    | '/_authenticated/transactions_/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/charges': {
      id: '/_authenticated/charges'
      path: '/charges'
      fullPath: '/charges'
      preLoaderRoute: typeof AuthenticatedChargesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions_/import': {
      id: '/_authenticated/transactions_/import'
      path: '/transactions/import'
      fullPath: '/transactions/import'
      preLoaderRoute: typeof AuthenticatedTransactionsImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connect-with/$externalId': {
      id: '/_authenticated/connect-with/$externalId'
      path: '/connect-with/$externalId'
      fullPath: '/connect-with/$externalId'
      preLoaderRoute: typeof AuthenticatedConnectWithExternalIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedChargesRoute: typeof AuthenticatedChargesRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedConnectWithExternalIdRoute: typeof AuthenticatedConnectWithExternalIdRoute
  AuthenticatedTransactionsImportRoute: typeof AuthenticatedTransactionsImportRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedChargesRoute: AuthenticatedChargesRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedConnectWithExternalIdRoute:
    AuthenticatedConnectWithExternalIdRoute,
  AuthenticatedTransactionsImportRoute: AuthenticatedTransactionsImportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
