export const QueryKeys = {
  Me: 'me',
  Transactions: 'transactions',
  Balance: 'balance',
  Accounts: 'accounts',
  Categories: 'categories',
  Tags: 'tags',
  InviteInfo: 'invite-info',
  UserConnections: 'user-connections',
  Charges: 'charges',
  ChargesPendingCount: 'charges-pending-count',
  Onboarding: 'onboarding',
  CheckDuplicate: 'check-duplicate',
  PushSubscription: 'push-subscription',
} as const
