export const QueryKeys = {
  Me: "me",
  Transactions: "transactions",
  Balance: "balance",
  Accounts: "accounts",
  AccountDeletionInfo: "account-deletion-info",
  Categories: "categories",
  Tags: "tags",
  InviteInfo: "invite-info",
  UserConnections: "user-connections",
  Charges: "charges",
  ChargesPendingCount: "charges-pending-count",
  Onboarding: "onboarding",
  CheckDuplicate: "check-duplicate",
  PushSubscription: "push-subscription",
  Notifications: "notifications",
  NotificationUnreadCount: "notification-unread-count",
  NotificationChargesById: "notification-charges-by-id",
  NotificationTransactionsById: "notification-transactions-by-id",
  AdminUsers: "admin-users",
  TransactionTemplates: "transaction-templates",
} as const;
